package com.linklife.dao;

import com.linklife.domain.ibator.AccountInfo;
import com.linklife.domain.ibator.AccountInfoExample;
import java.sql.SQLException;
import java.util.List;

public interface AccountInfoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_info
     *
     * @ibatorgenerated Sat Jan 03 16:09:10 CST 2015
     */
    int countByExample(AccountInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_info
     *
     * @ibatorgenerated Sat Jan 03 16:09:10 CST 2015
     */
    int deleteByExample(AccountInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_info
     *
     * @ibatorgenerated Sat Jan 03 16:09:10 CST 2015
     */
    int deleteByPrimaryKey(Integer accountId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_info
     *
     * @ibatorgenerated Sat Jan 03 16:09:10 CST 2015
     */
    Integer insert(AccountInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_info
     *
     * @ibatorgenerated Sat Jan 03 16:09:10 CST 2015
     */
    Integer insertSelective(AccountInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_info
     *
     * @ibatorgenerated Sat Jan 03 16:09:10 CST 2015
     */
    List selectByExample(AccountInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_info
     *
     * @ibatorgenerated Sat Jan 03 16:09:10 CST 2015
     */
    AccountInfo selectByPrimaryKey(Integer accountId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_info
     *
     * @ibatorgenerated Sat Jan 03 16:09:10 CST 2015
     */
    int updateByExampleSelective(AccountInfo record, AccountInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_info
     *
     * @ibatorgenerated Sat Jan 03 16:09:10 CST 2015
     */
    int updateByExample(AccountInfo record, AccountInfoExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_info
     *
     * @ibatorgenerated Sat Jan 03 16:09:10 CST 2015
     */
    int updateByPrimaryKeySelective(AccountInfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_info
     *
     * @ibatorgenerated Sat Jan 03 16:09:10 CST 2015
     */
    int updateByPrimaryKey(AccountInfo record) throws SQLException;
}