package com.linklife.dao;

import com.linklife.domain.ibator.AccountSuggest;
import com.linklife.domain.ibator.AccountSuggestExample;
import java.sql.SQLException;
import java.util.List;

public interface AccountSuggestDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_suggest
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    int countByExample(AccountSuggestExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_suggest
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    int deleteByExample(AccountSuggestExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_suggest
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    int deleteByPrimaryKey(Integer suggestId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_suggest
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    Integer insert(AccountSuggest record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_suggest
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    Integer insertSelective(AccountSuggest record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_suggest
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    List selectByExample(AccountSuggestExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_suggest
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    AccountSuggest selectByPrimaryKey(Integer suggestId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_suggest
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    int updateByExampleSelective(AccountSuggest record, AccountSuggestExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_suggest
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    int updateByExample(AccountSuggest record, AccountSuggestExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_suggest
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    int updateByPrimaryKeySelective(AccountSuggest record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table account_suggest
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    int updateByPrimaryKey(AccountSuggest record) throws SQLException;
}