package com.linklife.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.linklife.domain.ibator.LifeTrack;
import com.linklife.domain.ibator.LifeTrackExample;
import java.sql.SQLException;
import java.util.List;

public class LifeTrackDAOImpl implements LifeTrackDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table life_track
	 * @ibatorgenerated  Sun Aug 24 14:36:06 CST 2014
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table life_track
	 * @ibatorgenerated  Sun Aug 24 14:36:06 CST 2014
	 */
	public LifeTrackDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table life_track
	 * @ibatorgenerated  Sun Aug 24 14:36:06 CST 2014
	 */
	public int countByExample(LifeTrackExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"life_track.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table life_track
	 * @ibatorgenerated  Sun Aug 24 14:36:06 CST 2014
	 */
	public int deleteByExample(LifeTrackExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"life_track.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table life_track
	 * @ibatorgenerated  Sun Aug 24 14:36:06 CST 2014
	 */
	public int deleteByPrimaryKey(Integer trackId) throws SQLException {
		LifeTrack key = new LifeTrack();
		key.setTrackId(trackId);
		int rows = sqlMapClient.delete(
				"life_track.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table life_track
	 * @ibatorgenerated  Sun Aug 24 14:36:06 CST 2014
	 */
	public Integer insert(LifeTrack record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"life_track.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table life_track
	 * @ibatorgenerated  Sun Aug 24 14:36:06 CST 2014
	 */
	public Integer insertSelective(LifeTrack record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"life_track.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table life_track
	 * @ibatorgenerated  Sun Aug 24 14:36:06 CST 2014
	 */
	public List selectByExample(LifeTrackExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"life_track.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table life_track
	 * @ibatorgenerated  Sun Aug 24 14:36:06 CST 2014
	 */
	public LifeTrack selectByPrimaryKey(Integer trackId) throws SQLException {
		LifeTrack key = new LifeTrack();
		key.setTrackId(trackId);
		LifeTrack record = (LifeTrack) sqlMapClient.queryForObject(
				"life_track.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table life_track
	 * @ibatorgenerated  Sun Aug 24 14:36:06 CST 2014
	 */
	public int updateByExampleSelective(LifeTrack record,
			LifeTrackExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"life_track.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table life_track
	 * @ibatorgenerated  Sun Aug 24 14:36:06 CST 2014
	 */
	public int updateByExample(LifeTrack record, LifeTrackExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"life_track.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table life_track
	 * @ibatorgenerated  Sun Aug 24 14:36:06 CST 2014
	 */
	public int updateByPrimaryKeySelective(LifeTrack record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"life_track.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table life_track
	 * @ibatorgenerated  Sun Aug 24 14:36:06 CST 2014
	 */
	public int updateByPrimaryKey(LifeTrack record) throws SQLException {
		int rows = sqlMapClient.update(
				"life_track.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table life_track
	 * @ibatorgenerated  Sun Aug 24 14:36:06 CST 2014
	 */
	private static class UpdateByExampleParms extends LifeTrackExample {
		private Object record;

		public UpdateByExampleParms(Object record, LifeTrackExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}