package com.linklife.dao;

import com.linklife.domain.ibator.NuistChat;
import com.linklife.domain.ibator.NuistChatExample;
import java.sql.SQLException;
import java.util.List;

public interface NuistChatDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	int countByExample( NuistChatExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	int deleteByExample( NuistChatExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	int deleteByPrimaryKey( Integer chatId ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	Integer insert( NuistChat record ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	Integer insertSelective( NuistChat record ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	List selectByExample( NuistChatExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	NuistChat selectByPrimaryKey( Integer chatId ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	int updateByExampleSelective( NuistChat record, NuistChatExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	int updateByExample( NuistChat record, NuistChatExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	int updateByPrimaryKeySelective( NuistChat record ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	int updateByPrimaryKey( NuistChat record ) throws SQLException;
}