package com.linklife.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.linklife.domain.ibator.NuistCourse;
import com.linklife.domain.ibator.NuistCourseExample;
import java.sql.SQLException;
import java.util.List;

public class NuistCourseDAOImpl implements NuistCourseDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table nuist_course
     *
     * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_course
     *
     * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
     */
    public NuistCourseDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_course
     *
     * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
     */
    public int countByExample(NuistCourseExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("nuist_course.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_course
     *
     * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
     */
    public int deleteByExample(NuistCourseExample example) throws SQLException {
        int rows = sqlMapClient.delete("nuist_course.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_course
     *
     * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
     */
    public int deleteByPrimaryKey(Integer courseId) throws SQLException {
        NuistCourse key = new NuistCourse();
        key.setCourseId(courseId);
        int rows = sqlMapClient.delete("nuist_course.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_course
     *
     * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
     */
    public Integer insert(NuistCourse record) throws SQLException {
        Object newKey = sqlMapClient.insert("nuist_course.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_course
     *
     * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
     */
    public Integer insertSelective(NuistCourse record) throws SQLException {
        Object newKey = sqlMapClient.insert("nuist_course.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_course
     *
     * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
     */
    public List selectByExample(NuistCourseExample example) throws SQLException {
        List list = sqlMapClient.queryForList("nuist_course.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_course
     *
     * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
     */
    public NuistCourse selectByPrimaryKey(Integer courseId) throws SQLException {
        NuistCourse key = new NuistCourse();
        key.setCourseId(courseId);
        NuistCourse record = (NuistCourse) sqlMapClient.queryForObject("nuist_course.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_course
     *
     * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
     */
    public int updateByExampleSelective(NuistCourse record, NuistCourseExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("nuist_course.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_course
     *
     * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
     */
    public int updateByExample(NuistCourse record, NuistCourseExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("nuist_course.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_course
     *
     * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
     */
    public int updateByPrimaryKeySelective(NuistCourse record) throws SQLException {
        int rows = sqlMapClient.update("nuist_course.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_course
     *
     * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
     */
    public int updateByPrimaryKey(NuistCourse record) throws SQLException {
        int rows = sqlMapClient.update("nuist_course.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table nuist_course
     *
     * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
     */
    private static class UpdateByExampleParms extends NuistCourseExample {
        private Object record;

        public UpdateByExampleParms(Object record, NuistCourseExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}