package com.linklife.dao;

import com.linklife.domain.ibator.NuistClass;
import com.linklife.domain.ibator.NuistClassExample;
import java.sql.SQLException;
import java.util.List;

public interface NuistClassDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    int countByExample(NuistClassExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    int deleteByExample(NuistClassExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    int deleteByPrimaryKey(Integer classId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    Integer insert(NuistClass record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    Integer insertSelective(NuistClass record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    List selectByExample(NuistClassExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    NuistClass selectByPrimaryKey(Integer classId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    int updateByExampleSelective(NuistClass record, NuistClassExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    int updateByExample(NuistClass record, NuistClassExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    int updateByPrimaryKeySelective(NuistClass record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    int updateByPrimaryKey(NuistClass record) throws SQLException;
}