package com.linklife.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.linklife.domain.ibator.NuistTestHistory;
import com.linklife.domain.ibator.NuistTestHistoryExample;
import java.sql.SQLException;
import java.util.List;

public class NuistTestHistoryDAOImpl implements NuistTestHistoryDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    public NuistTestHistoryDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    public int countByExample(NuistTestHistoryExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("nuist_test.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    public int deleteByExample(NuistTestHistoryExample example) throws SQLException {
        int rows = sqlMapClient.delete("nuist_test.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    public int deleteByPrimaryKey(Integer testId) throws SQLException {
        NuistTestHistory key = new NuistTestHistory();
        key.setTestId(testId);
        int rows = sqlMapClient.delete("nuist_test.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    public Integer insert(NuistTestHistory record) throws SQLException {
        Object newKey = sqlMapClient.insert("nuist_test.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    public Integer insertSelective(NuistTestHistory record) throws SQLException {
        Object newKey = sqlMapClient.insert("nuist_test.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    public List selectByExample(NuistTestHistoryExample example) throws SQLException {
        List list = sqlMapClient.queryForList("nuist_test.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    public NuistTestHistory selectByPrimaryKey(Integer testId) throws SQLException {
        NuistTestHistory key = new NuistTestHistory();
        key.setTestId(testId);
        NuistTestHistory record = (NuistTestHistory) sqlMapClient.queryForObject("nuist_test.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    public int updateByExampleSelective(NuistTestHistory record, NuistTestHistoryExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("nuist_test.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    public int updateByExample(NuistTestHistory record, NuistTestHistoryExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("nuist_test.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    public int updateByPrimaryKeySelective(NuistTestHistory record) throws SQLException {
        int rows = sqlMapClient.update("nuist_test.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    public int updateByPrimaryKey(NuistTestHistory record) throws SQLException {
        int rows = sqlMapClient.update("nuist_test.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    private static class UpdateByExampleParms extends NuistTestHistoryExample {
        private Object record;

        public UpdateByExampleParms(Object record, NuistTestHistoryExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}