package com.linklife.dao;

import com.linklife.domain.ibator.NuistSuggest;
import com.linklife.domain.ibator.NuistSuggestExample;
import java.sql.SQLException;
import java.util.List;

public interface NuistSuggestDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_suggest
	 * @ibatorgenerated  Mon Feb 09 19:40:42 CST 2015
	 */
	int countByExample( NuistSuggestExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_suggest
	 * @ibatorgenerated  Mon Feb 09 19:40:42 CST 2015
	 */
	int deleteByExample( NuistSuggestExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_suggest
	 * @ibatorgenerated  Mon Feb 09 19:40:42 CST 2015
	 */
	int deleteByPrimaryKey( Integer suggestId ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_suggest
	 * @ibatorgenerated  Mon Feb 09 19:40:42 CST 2015
	 */
	Integer insert( NuistSuggest record ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_suggest
	 * @ibatorgenerated  Mon Feb 09 19:40:42 CST 2015
	 */
	Integer insertSelective( NuistSuggest record ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_suggest
	 * @ibatorgenerated  Mon Feb 09 19:40:42 CST 2015
	 */
	List selectByExample( NuistSuggestExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_suggest
	 * @ibatorgenerated  Mon Feb 09 19:40:42 CST 2015
	 */
	NuistSuggest selectByPrimaryKey( Integer suggestId ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_suggest
	 * @ibatorgenerated  Mon Feb 09 19:40:42 CST 2015
	 */
	int updateByExampleSelective( NuistSuggest record, NuistSuggestExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_suggest
	 * @ibatorgenerated  Mon Feb 09 19:40:42 CST 2015
	 */
	int updateByExample( NuistSuggest record, NuistSuggestExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_suggest
	 * @ibatorgenerated  Mon Feb 09 19:40:42 CST 2015
	 */
	int updateByPrimaryKeySelective( NuistSuggest record ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_suggest
	 * @ibatorgenerated  Mon Feb 09 19:40:42 CST 2015
	 */
	int updateByPrimaryKey( NuistSuggest record ) throws SQLException;
}