package com.linklife.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.linklife.domain.ibator.NuistChat;
import com.linklife.domain.ibator.NuistChatExample;
import java.sql.SQLException;
import java.util.List;

public class NuistChatDAOImpl implements NuistChatDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public NuistChatDAOImpl( SqlMapClient sqlMapClient ) {

		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public int countByExample( NuistChatExample example ) throws SQLException {

		Integer count = ( Integer )sqlMapClient.queryForObject( "nuist_chat.ibatorgenerated_countByExample", example );
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public int deleteByExample( NuistChatExample example ) throws SQLException {

		int rows = sqlMapClient.delete( "nuist_chat.ibatorgenerated_deleteByExample", example );
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public int deleteByPrimaryKey( Integer chatId ) throws SQLException {

		NuistChat key = new NuistChat();
		key.setChatId( chatId );
		int rows = sqlMapClient.delete( "nuist_chat.ibatorgenerated_deleteByPrimaryKey", key );
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public Integer insert( NuistChat record ) throws SQLException {

		Object newKey = sqlMapClient.insert( "nuist_chat.ibatorgenerated_insert", record );
		return ( Integer )newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public Integer insertSelective( NuistChat record ) throws SQLException {

		Object newKey = sqlMapClient.insert( "nuist_chat.ibatorgenerated_insertSelective", record );
		return ( Integer )newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public List selectByExample( NuistChatExample example ) throws SQLException {

		List list = sqlMapClient.queryForList( "nuist_chat.ibatorgenerated_selectByExample", example );
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public NuistChat selectByPrimaryKey( Integer chatId ) throws SQLException {

		NuistChat key = new NuistChat();
		key.setChatId( chatId );
		NuistChat record = ( NuistChat )sqlMapClient.queryForObject( "nuist_chat.ibatorgenerated_selectByPrimaryKey", key );
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public int updateByExampleSelective( NuistChat record, NuistChatExample example ) throws SQLException {

		UpdateByExampleParms parms = new UpdateByExampleParms( record, example );
		int rows = sqlMapClient.update( "nuist_chat.ibatorgenerated_updateByExampleSelective", parms );
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public int updateByExample( NuistChat record, NuistChatExample example ) throws SQLException {

		UpdateByExampleParms parms = new UpdateByExampleParms( record, example );
		int rows = sqlMapClient.update( "nuist_chat.ibatorgenerated_updateByExample", parms );
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public int updateByPrimaryKeySelective( NuistChat record ) throws SQLException {

		int rows = sqlMapClient.update( "nuist_chat.ibatorgenerated_updateByPrimaryKeySelective", record );
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public int updateByPrimaryKey( NuistChat record ) throws SQLException {

		int rows = sqlMapClient.update( "nuist_chat.ibatorgenerated_updateByPrimaryKey", record );
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	private static class UpdateByExampleParms extends NuistChatExample {

		private Object record;


		public UpdateByExampleParms( Object record, NuistChatExample example ) {

			super( example );
			this.record = record;
		}


		public Object getRecord() {

			return record;
		}
	}
}