package com.linklife.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.linklife.domain.ibator.NuistClass;
import com.linklife.domain.ibator.NuistClassExample;
import java.sql.SQLException;
import java.util.List;

public class NuistClassDAOImpl implements NuistClassDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    public NuistClassDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    public int countByExample(NuistClassExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("nuist_class.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    public int deleteByExample(NuistClassExample example) throws SQLException {
        int rows = sqlMapClient.delete("nuist_class.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    public int deleteByPrimaryKey(Integer classId) throws SQLException {
        NuistClass key = new NuistClass();
        key.setClassId(classId);
        int rows = sqlMapClient.delete("nuist_class.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    public Integer insert(NuistClass record) throws SQLException {
        Object newKey = sqlMapClient.insert("nuist_class.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    public Integer insertSelective(NuistClass record) throws SQLException {
        Object newKey = sqlMapClient.insert("nuist_class.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    public List selectByExample(NuistClassExample example) throws SQLException {
        List list = sqlMapClient.queryForList("nuist_class.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    public NuistClass selectByPrimaryKey(Integer classId) throws SQLException {
        NuistClass key = new NuistClass();
        key.setClassId(classId);
        NuistClass record = (NuistClass) sqlMapClient.queryForObject("nuist_class.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    public int updateByExampleSelective(NuistClass record, NuistClassExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("nuist_class.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    public int updateByExample(NuistClass record, NuistClassExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("nuist_class.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    public int updateByPrimaryKeySelective(NuistClass record) throws SQLException {
        int rows = sqlMapClient.update("nuist_class.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    public int updateByPrimaryKey(NuistClass record) throws SQLException {
        int rows = sqlMapClient.update("nuist_class.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table nuist_class
     *
     * @ibatorgenerated Sun Jul 12 21:12:30 CST 2015
     */
    private static class UpdateByExampleParms extends NuistClassExample {
        private Object record;

        public UpdateByExampleParms(Object record, NuistClassExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}