package com.linklife.dao;

import com.linklife.domain.ibator.NuistLoginHistory;
import com.linklife.domain.ibator.NuistLoginHistoryExample;
import java.sql.SQLException;
import java.util.List;

public interface NuistLoginHistoryDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login_history
	 * @ibatorgenerated  Tue Jan 27 09:10:44 CST 2015
	 */
	int countByExample( NuistLoginHistoryExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login_history
	 * @ibatorgenerated  Tue Jan 27 09:10:44 CST 2015
	 */
	int deleteByExample( NuistLoginHistoryExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login_history
	 * @ibatorgenerated  Tue Jan 27 09:10:44 CST 2015
	 */
	int deleteByPrimaryKey( Integer signinId ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login_history
	 * @ibatorgenerated  Tue Jan 27 09:10:44 CST 2015
	 */
	Integer insert( NuistLoginHistory record ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login_history
	 * @ibatorgenerated  Tue Jan 27 09:10:44 CST 2015
	 */
	Integer insertSelective( NuistLoginHistory record ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login_history
	 * @ibatorgenerated  Tue Jan 27 09:10:44 CST 2015
	 */
	List selectByExample( NuistLoginHistoryExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login_history
	 * @ibatorgenerated  Tue Jan 27 09:10:44 CST 2015
	 */
	NuistLoginHistory selectByPrimaryKey( Integer signinId ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login_history
	 * @ibatorgenerated  Tue Jan 27 09:10:44 CST 2015
	 */
	int updateByExampleSelective( NuistLoginHistory record, NuistLoginHistoryExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login_history
	 * @ibatorgenerated  Tue Jan 27 09:10:44 CST 2015
	 */
	int updateByExample( NuistLoginHistory record, NuistLoginHistoryExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login_history
	 * @ibatorgenerated  Tue Jan 27 09:10:44 CST 2015
	 */
	int updateByPrimaryKeySelective( NuistLoginHistory record ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login_history
	 * @ibatorgenerated  Tue Jan 27 09:10:44 CST 2015
	 */
	int updateByPrimaryKey( NuistLoginHistory record ) throws SQLException;
}