package com.linklife.dao;

import com.linklife.domain.ibator.NuistTestHistory;
import com.linklife.domain.ibator.NuistTestHistoryExample;
import java.sql.SQLException;
import java.util.List;

public interface NuistTestHistoryDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    int countByExample(NuistTestHistoryExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    int deleteByExample(NuistTestHistoryExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    int deleteByPrimaryKey(Integer testId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    Integer insert(NuistTestHistory record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    Integer insertSelective(NuistTestHistory record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    List selectByExample(NuistTestHistoryExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    NuistTestHistory selectByPrimaryKey(Integer testId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    int updateByExampleSelective(NuistTestHistory record, NuistTestHistoryExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    int updateByExample(NuistTestHistory record, NuistTestHistoryExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    int updateByPrimaryKeySelective(NuistTestHistory record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_test
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    int updateByPrimaryKey(NuistTestHistory record) throws SQLException;
}