package com.linklife.dao;

import com.linklife.domain.ibator.NuistScoreHistory;
import com.linklife.domain.ibator.NuistScoreHistoryExample;
import java.sql.SQLException;
import java.util.List;

public interface NuistScoreHistoryDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_score_history
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	int countByExample( NuistScoreHistoryExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_score_history
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	int deleteByExample( NuistScoreHistoryExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_score_history
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	int deleteByPrimaryKey( Long scoreId ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_score_history
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	Long insert( NuistScoreHistory record ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_score_history
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	Long insertSelective( NuistScoreHistory record ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_score_history
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	List selectByExample( NuistScoreHistoryExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_score_history
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	NuistScoreHistory selectByPrimaryKey( Long scoreId ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_score_history
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	int updateByExampleSelective( NuistScoreHistory record, NuistScoreHistoryExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_score_history
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	int updateByExample( NuistScoreHistory record, NuistScoreHistoryExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_score_history
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	int updateByPrimaryKeySelective( NuistScoreHistory record ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_score_history
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	int updateByPrimaryKey( NuistScoreHistory record ) throws SQLException;
}