package com.linklife.dao;

import com.linklife.domain.ibator.NuistTradeHistory;
import com.linklife.domain.ibator.NuistTradeHistoryExample;
import java.sql.SQLException;
import java.util.List;

public interface NuistTradeHistoryDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_trade_history
	 * @ibatorgenerated  Sun Jul 12 10:32:21 CST 2015
	 */
	int countByExample( NuistTradeHistoryExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_trade_history
	 * @ibatorgenerated  Sun Jul 12 10:32:21 CST 2015
	 */
	int deleteByExample( NuistTradeHistoryExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_trade_history
	 * @ibatorgenerated  Sun Jul 12 10:32:21 CST 2015
	 */
	int deleteByPrimaryKey( Integer tradeId ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_trade_history
	 * @ibatorgenerated  Sun Jul 12 10:32:21 CST 2015
	 */
	Integer insert( NuistTradeHistory record ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_trade_history
	 * @ibatorgenerated  Sun Jul 12 10:32:21 CST 2015
	 */
	Integer insertSelective( NuistTradeHistory record ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_trade_history
	 * @ibatorgenerated  Sun Jul 12 10:32:21 CST 2015
	 */
	List selectByExample( NuistTradeHistoryExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_trade_history
	 * @ibatorgenerated  Sun Jul 12 10:32:21 CST 2015
	 */
	NuistTradeHistory selectByPrimaryKey( Integer tradeId ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_trade_history
	 * @ibatorgenerated  Sun Jul 12 10:32:21 CST 2015
	 */
	int updateByExampleSelective( NuistTradeHistory record, NuistTradeHistoryExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_trade_history
	 * @ibatorgenerated  Sun Jul 12 10:32:21 CST 2015
	 */
	int updateByExample( NuistTradeHistory record, NuistTradeHistoryExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_trade_history
	 * @ibatorgenerated  Sun Jul 12 10:32:21 CST 2015
	 */
	int updateByPrimaryKeySelective( NuistTradeHistory record ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_trade_history
	 * @ibatorgenerated  Sun Jul 12 10:32:21 CST 2015
	 */
	int updateByPrimaryKey( NuistTradeHistory record ) throws SQLException;
}