package com.linklife.dao;

import com.linklife.domain.ibator.NuistLogin;
import com.linklife.domain.ibator.NuistLoginExample;
import java.sql.SQLException;
import java.util.List;

public interface NuistLoginDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login
	 * @ibatorgenerated  Sun Jul 12 10:23:21 CST 2015
	 */
	int countByExample( NuistLoginExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login
	 * @ibatorgenerated  Sun Jul 12 10:23:21 CST 2015
	 */
	int deleteByExample( NuistLoginExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login
	 * @ibatorgenerated  Sun Jul 12 10:23:21 CST 2015
	 */
	int deleteByPrimaryKey( String usernumber ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login
	 * @ibatorgenerated  Sun Jul 12 10:23:21 CST 2015
	 */
	String insert( NuistLogin record ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login
	 * @ibatorgenerated  Sun Jul 12 10:23:21 CST 2015
	 */
	String insertSelective( NuistLogin record ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login
	 * @ibatorgenerated  Sun Jul 12 10:23:21 CST 2015
	 */
	List selectByExample( NuistLoginExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login
	 * @ibatorgenerated  Sun Jul 12 10:23:21 CST 2015
	 */
	NuistLogin selectByPrimaryKey( String usernumber ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login
	 * @ibatorgenerated  Sun Jul 12 10:23:21 CST 2015
	 */
	int updateByExampleSelective( NuistLogin record, NuistLoginExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login
	 * @ibatorgenerated  Sun Jul 12 10:23:21 CST 2015
	 */
	int updateByExample( NuistLogin record, NuistLoginExample example ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login
	 * @ibatorgenerated  Sun Jul 12 10:23:21 CST 2015
	 */
	int updateByPrimaryKeySelective( NuistLogin record ) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_login
	 * @ibatorgenerated  Sun Jul 12 10:23:21 CST 2015
	 */
	int updateByPrimaryKey( NuistLogin record ) throws SQLException;
}