package com.linklife.dao;

import com.linklife.domain.ibator.NuistShop;
import com.linklife.domain.ibator.NuistShopExample;
import java.sql.SQLException;
import java.util.List;

public interface NuistShopDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_shop
     *
     * @ibatorgenerated Sun Jul 12 13:22:20 CST 2015
     */
    int countByExample(NuistShopExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_shop
     *
     * @ibatorgenerated Sun Jul 12 13:22:20 CST 2015
     */
    int deleteByExample(NuistShopExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_shop
     *
     * @ibatorgenerated Sun Jul 12 13:22:20 CST 2015
     */
    int deleteByPrimaryKey(Integer shopId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_shop
     *
     * @ibatorgenerated Sun Jul 12 13:22:20 CST 2015
     */
    Integer insert(NuistShop record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_shop
     *
     * @ibatorgenerated Sun Jul 12 13:22:20 CST 2015
     */
    Integer insertSelective(NuistShop record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_shop
     *
     * @ibatorgenerated Sun Jul 12 13:22:20 CST 2015
     */
    List selectByExample(NuistShopExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_shop
     *
     * @ibatorgenerated Sun Jul 12 13:22:20 CST 2015
     */
    NuistShop selectByPrimaryKey(Integer shopId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_shop
     *
     * @ibatorgenerated Sun Jul 12 13:22:20 CST 2015
     */
    int updateByExampleSelective(NuistShop record, NuistShopExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_shop
     *
     * @ibatorgenerated Sun Jul 12 13:22:20 CST 2015
     */
    int updateByExample(NuistShop record, NuistShopExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_shop
     *
     * @ibatorgenerated Sun Jul 12 13:22:20 CST 2015
     */
    int updateByPrimaryKeySelective(NuistShop record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table nuist_shop
     *
     * @ibatorgenerated Sun Jul 12 13:22:20 CST 2015
     */
    int updateByPrimaryKey(NuistShop record) throws SQLException;
}