package com.linklife.dao;

import com.linklife.domain.ibator.SearchHistory;
import com.linklife.domain.ibator.SearchHistoryExample;
import java.sql.SQLException;
import java.util.List;

public interface SearchHistoryDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	int countByExample(SearchHistoryExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	int deleteByExample(SearchHistoryExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	int deleteByPrimaryKey(Integer searchId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	Integer insert(SearchHistory record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	Integer insertSelective(SearchHistory record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	List selectByExample(SearchHistoryExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	SearchHistory selectByPrimaryKey(Integer searchId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	int updateByExampleSelective(SearchHistory record,
			SearchHistoryExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	int updateByExample(SearchHistory record, SearchHistoryExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	int updateByPrimaryKeySelective(SearchHistory record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	int updateByPrimaryKey(SearchHistory record) throws SQLException;
}