package com.linklife.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.linklife.domain.ibator.SearchHistory;
import com.linklife.domain.ibator.SearchHistoryExample;
import java.sql.SQLException;
import java.util.List;

public class SearchHistoryDAOImpl implements SearchHistoryDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public SearchHistoryDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public int countByExample(SearchHistoryExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"search_history.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public int deleteByExample(SearchHistoryExample example)
			throws SQLException {
		int rows = sqlMapClient.delete(
				"search_history.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public int deleteByPrimaryKey(Integer searchId) throws SQLException {
		SearchHistory key = new SearchHistory();
		key.setSearchId(searchId);
		int rows = sqlMapClient.delete(
				"search_history.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public Integer insert(SearchHistory record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"search_history.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public Integer insertSelective(SearchHistory record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"search_history.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public List selectByExample(SearchHistoryExample example)
			throws SQLException {
		List list = sqlMapClient.queryForList(
				"search_history.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public SearchHistory selectByPrimaryKey(Integer searchId)
			throws SQLException {
		SearchHistory key = new SearchHistory();
		key.setSearchId(searchId);
		SearchHistory record = (SearchHistory) sqlMapClient.queryForObject(
				"search_history.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public int updateByExampleSelective(SearchHistory record,
			SearchHistoryExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"search_history.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public int updateByExample(SearchHistory record,
			SearchHistoryExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"search_history.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public int updateByPrimaryKeySelective(SearchHistory record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"search_history.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public int updateByPrimaryKey(SearchHistory record) throws SQLException {
		int rows = sqlMapClient.update(
				"search_history.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table search_history
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	private static class UpdateByExampleParms extends SearchHistoryExample {
		private Object record;

		public UpdateByExampleParms(Object record, SearchHistoryExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}