package com.linklife.domain.ibator;

import java.util.Date;

import com.linklife.domain.base.BaseDomain;
import com.linklife.repository.base.SqlMap;

/**
 * <p>
 * AccountSuggest.java
 * </p>
 * 
 * <pre>
 * 用户建议表对应实体类
 * </pre>
 * 
 * @author caisupeng
 */
@SqlMap(Name = "account_suggest", Class = AccountSuggest.class)
public class AccountSuggest<T, U> extends BaseDomain<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column account_suggest.suggest_id
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    private Integer suggestId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column account_suggest.acount_id
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    private Integer acountId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column account_suggest.suggest
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    private String suggest;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column account_suggest.add_time
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    private Date addTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column account_suggest.add_ip
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    private String addIp;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column account_suggest.suggest_id
     *
     * @return the value of account_suggest.suggest_id
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    public Integer getSuggestId() {
        return suggestId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column account_suggest.suggest_id
     *
     * @param suggestId the value for account_suggest.suggest_id
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    public void setSuggestId(Integer suggestId) {
        this.suggestId = suggestId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column account_suggest.acount_id
     *
     * @return the value of account_suggest.acount_id
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    public Integer getAcountId() {
        return acountId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column account_suggest.acount_id
     *
     * @param acountId the value for account_suggest.acount_id
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    public void setAcountId(Integer acountId) {
        this.acountId = acountId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column account_suggest.suggest
     *
     * @return the value of account_suggest.suggest
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    public String getSuggest() {
        return suggest;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column account_suggest.suggest
     *
     * @param suggest the value for account_suggest.suggest
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    public void setSuggest(String suggest) {
        this.suggest = suggest;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column account_suggest.add_time
     *
     * @return the value of account_suggest.add_time
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column account_suggest.add_time
     *
     * @param addTime the value for account_suggest.add_time
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column account_suggest.add_ip
     *
     * @return the value of account_suggest.add_ip
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    public String getAddIp() {
        return addIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column account_suggest.add_ip
     *
     * @param addIp the value for account_suggest.add_ip
     *
     * @ibatorgenerated Sun Aug 24 16:58:06 CST 2014
     */
    public void setAddIp(String addIp) {
        this.addIp = addIp;
    }
}