package com.linklife.domain.ibator;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * <p>
 * AccountInfo.java
 * </p>
 * 
 * <pre>
 * 用户信息表对应实体Example�?
 * </pre>
 * 
 * @author caisupeng
 */
public class AccountInfoExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table account_info
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table account_info
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table account_info
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public AccountInfoExample() {

		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table account_info
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	protected AccountInfoExample( AccountInfoExample example ) {

		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table account_info
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public void setOrderByClause( String orderByClause ) {

		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table account_info
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public String getOrderByClause() {

		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table account_info
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public List getOredCriteria() {

		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table account_info
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public void or( Criteria criteria ) {

		oredCriteria.add( criteria );
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table account_info
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public Criteria createCriteria() {

		Criteria criteria = createCriteriaInternal();
		if( oredCriteria.size() == 0 ) {
			oredCriteria.add( criteria );
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table account_info
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	protected Criteria createCriteriaInternal() {

		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table account_info
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public void clear() {

		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table account_info
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public static class Criteria {

		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;


		protected Criteria() {

			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}


		public boolean isValid() {

			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}


		public List getCriteriaWithoutValue() {

			return criteriaWithoutValue;
		}


		public List getCriteriaWithSingleValue() {

			return criteriaWithSingleValue;
		}


		public List getCriteriaWithListValue() {

			return criteriaWithListValue;
		}


		public List getCriteriaWithBetweenValue() {

			return criteriaWithBetweenValue;
		}


		protected void addCriterion( String condition ) {

			if( condition == null ) {
				throw new RuntimeException( "Value for condition cannot be null" );
			}
			criteriaWithoutValue.add( condition );
		}


		protected void addCriterion( String condition, Object value, String property ) {

			if( value == null ) {
				throw new RuntimeException( "Value for " + property + " cannot be null" );
			}
			Map map = new HashMap();
			map.put( "condition", condition );
			map.put( "value", value );
			criteriaWithSingleValue.add( map );
		}


		protected void addCriterion( String condition, List values, String property ) {

			if( values == null || values.size() == 0 ) {
				throw new RuntimeException( "Value list for " + property + " cannot be null or empty" );
			}
			Map map = new HashMap();
			map.put( "condition", condition );
			map.put( "values", values );
			criteriaWithListValue.add( map );
		}


		protected void addCriterion( String condition, Object value1, Object value2, String property ) {

			if( value1 == null || value2 == null ) {
				throw new RuntimeException( "Between values for " + property + " cannot be null" );
			}
			List list = new ArrayList();
			list.add( value1 );
			list.add( value2 );
			Map map = new HashMap();
			map.put( "condition", condition );
			map.put( "values", list );
			criteriaWithBetweenValue.add( map );
		}


		public Criteria andAccountIdIsNull() {

			addCriterion( "account_id is null" );
			return this;
		}


		public Criteria andAccountIdIsNotNull() {

			addCriterion( "account_id is not null" );
			return this;
		}


		public Criteria andAccountIdEqualTo( Integer value ) {

			addCriterion( "account_id =", value, "accountId" );
			return this;
		}


		public Criteria andAccountIdNotEqualTo( Integer value ) {

			addCriterion( "account_id <>", value, "accountId" );
			return this;
		}


		public Criteria andAccountIdGreaterThan( Integer value ) {

			addCriterion( "account_id >", value, "accountId" );
			return this;
		}


		public Criteria andAccountIdGreaterThanOrEqualTo( Integer value ) {

			addCriterion( "account_id >=", value, "accountId" );
			return this;
		}


		public Criteria andAccountIdLessThan( Integer value ) {

			addCriterion( "account_id <", value, "accountId" );
			return this;
		}


		public Criteria andAccountIdLessThanOrEqualTo( Integer value ) {

			addCriterion( "account_id <=", value, "accountId" );
			return this;
		}


		public Criteria andAccountIdIn( List values ) {

			addCriterion( "account_id in", values, "accountId" );
			return this;
		}


		public Criteria andAccountIdNotIn( List values ) {

			addCriterion( "account_id not in", values, "accountId" );
			return this;
		}


		public Criteria andAccountIdBetween( Integer value1, Integer value2 ) {

			addCriterion( "account_id between", value1, value2, "accountId" );
			return this;
		}


		public Criteria andAccountIdNotBetween( Integer value1, Integer value2 ) {

			addCriterion( "account_id not between", value1, value2, "accountId" );
			return this;
		}


		public Criteria andNameIsNull() {

			addCriterion( "name is null" );
			return this;
		}


		public Criteria andNameIsNotNull() {

			addCriterion( "name is not null" );
			return this;
		}


		public Criteria andNameEqualTo( String value ) {

			addCriterion( "name =", value, "name" );
			return this;
		}


		public Criteria andNameNotEqualTo( String value ) {

			addCriterion( "name <>", value, "name" );
			return this;
		}


		public Criteria andNameGreaterThan( String value ) {

			addCriterion( "name >", value, "name" );
			return this;
		}


		public Criteria andNameGreaterThanOrEqualTo( String value ) {

			addCriterion( "name >=", value, "name" );
			return this;
		}


		public Criteria andNameLessThan( String value ) {

			addCriterion( "name <", value, "name" );
			return this;
		}


		public Criteria andNameLessThanOrEqualTo( String value ) {

			addCriterion( "name <=", value, "name" );
			return this;
		}


		public Criteria andNameLike( String value ) {

			addCriterion( "name like", value, "name" );
			return this;
		}


		public Criteria andNameNotLike( String value ) {

			addCriterion( "name not like", value, "name" );
			return this;
		}


		public Criteria andNameIn( List values ) {

			addCriterion( "name in", values, "name" );
			return this;
		}


		public Criteria andNameNotIn( List values ) {

			addCriterion( "name not in", values, "name" );
			return this;
		}


		public Criteria andNameBetween( String value1, String value2 ) {

			addCriterion( "name between", value1, value2, "name" );
			return this;
		}


		public Criteria andNameNotBetween( String value1, String value2 ) {

			addCriterion( "name not between", value1, value2, "name" );
			return this;
		}


		public Criteria andBirthdayIsNull() {

			addCriterion( "birthday is null" );
			return this;
		}


		public Criteria andBirthdayIsNotNull() {

			addCriterion( "birthday is not null" );
			return this;
		}


		public Criteria andBirthdayEqualTo( Date value ) {

			addCriterion( "birthday =", value, "birthday" );
			return this;
		}


		public Criteria andBirthdayNotEqualTo( Date value ) {

			addCriterion( "birthday <>", value, "birthday" );
			return this;
		}


		public Criteria andBirthdayGreaterThan( Date value ) {

			addCriterion( "birthday >", value, "birthday" );
			return this;
		}


		public Criteria andBirthdayGreaterThanOrEqualTo( Date value ) {

			addCriterion( "birthday >=", value, "birthday" );
			return this;
		}


		public Criteria andBirthdayLessThan( Date value ) {

			addCriterion( "birthday <", value, "birthday" );
			return this;
		}


		public Criteria andBirthdayLessThanOrEqualTo( Date value ) {

			addCriterion( "birthday <=", value, "birthday" );
			return this;
		}


		public Criteria andBirthdayIn( List values ) {

			addCriterion( "birthday in", values, "birthday" );
			return this;
		}


		public Criteria andBirthdayNotIn( List values ) {

			addCriterion( "birthday not in", values, "birthday" );
			return this;
		}


		public Criteria andBirthdayBetween( Date value1, Date value2 ) {

			addCriterion( "birthday between", value1, value2, "birthday" );
			return this;
		}


		public Criteria andBirthdayNotBetween( Date value1, Date value2 ) {

			addCriterion( "birthday not between", value1, value2, "birthday" );
			return this;
		}


		public Criteria andAuthorityIsNull() {

			addCriterion( "authority is null" );
			return this;
		}


		public Criteria andAuthorityIsNotNull() {

			addCriterion( "authority is not null" );
			return this;
		}


		public Criteria andAuthorityEqualTo( String value ) {

			addCriterion( "authority =", value, "authority" );
			return this;
		}


		public Criteria andAuthorityNotEqualTo( String value ) {

			addCriterion( "authority <>", value, "authority" );
			return this;
		}


		public Criteria andAuthorityGreaterThan( String value ) {

			addCriterion( "authority >", value, "authority" );
			return this;
		}


		public Criteria andAuthorityGreaterThanOrEqualTo( String value ) {

			addCriterion( "authority >=", value, "authority" );
			return this;
		}


		public Criteria andAuthorityLessThan( String value ) {

			addCriterion( "authority <", value, "authority" );
			return this;
		}


		public Criteria andAuthorityLessThanOrEqualTo( String value ) {

			addCriterion( "authority <=", value, "authority" );
			return this;
		}


		public Criteria andAuthorityLike( String value ) {

			addCriterion( "authority like", value, "authority" );
			return this;
		}


		public Criteria andAuthorityNotLike( String value ) {

			addCriterion( "authority not like", value, "authority" );
			return this;
		}


		public Criteria andAuthorityIn( List values ) {

			addCriterion( "authority in", values, "authority" );
			return this;
		}


		public Criteria andAuthorityNotIn( List values ) {

			addCriterion( "authority not in", values, "authority" );
			return this;
		}


		public Criteria andAuthorityBetween( String value1, String value2 ) {

			addCriterion( "authority between", value1, value2, "authority" );
			return this;
		}


		public Criteria andAuthorityNotBetween( String value1, String value2 ) {

			addCriterion( "authority not between", value1, value2, "authority" );
			return this;
		}


		public Criteria andAddTimeIsNull() {

			addCriterion( "add_time is null" );
			return this;
		}


		public Criteria andAddTimeIsNotNull() {

			addCriterion( "add_time is not null" );
			return this;
		}


		public Criteria andAddTimeEqualTo( Date value ) {

			addCriterion( "add_time =", value, "addTime" );
			return this;
		}


		public Criteria andAddTimeNotEqualTo( Date value ) {

			addCriterion( "add_time <>", value, "addTime" );
			return this;
		}


		public Criteria andAddTimeGreaterThan( Date value ) {

			addCriterion( "add_time >", value, "addTime" );
			return this;
		}


		public Criteria andAddTimeGreaterThanOrEqualTo( Date value ) {

			addCriterion( "add_time >=", value, "addTime" );
			return this;
		}


		public Criteria andAddTimeLessThan( Date value ) {

			addCriterion( "add_time <", value, "addTime" );
			return this;
		}


		public Criteria andAddTimeLessThanOrEqualTo( Date value ) {

			addCriterion( "add_time <=", value, "addTime" );
			return this;
		}


		public Criteria andAddTimeIn( List values ) {

			addCriterion( "add_time in", values, "addTime" );
			return this;
		}


		public Criteria andAddTimeNotIn( List values ) {

			addCriterion( "add_time not in", values, "addTime" );
			return this;
		}


		public Criteria andAddTimeBetween( Date value1, Date value2 ) {

			addCriterion( "add_time between", value1, value2, "addTime" );
			return this;
		}


		public Criteria andAddTimeNotBetween( Date value1, Date value2 ) {

			addCriterion( "add_time not between", value1, value2, "addTime" );
			return this;
		}


		public Criteria andAddLocationIsNull() {

			addCriterion( "add_location is null" );
			return this;
		}


		public Criteria andAddLocationIsNotNull() {

			addCriterion( "add_location is not null" );
			return this;
		}


		public Criteria andAddLocationEqualTo( String value ) {

			addCriterion( "add_location =", value, "addLocation" );
			return this;
		}


		public Criteria andAddLocationNotEqualTo( String value ) {

			addCriterion( "add_location <>", value, "addLocation" );
			return this;
		}


		public Criteria andAddLocationGreaterThan( String value ) {

			addCriterion( "add_location >", value, "addLocation" );
			return this;
		}


		public Criteria andAddLocationGreaterThanOrEqualTo( String value ) {

			addCriterion( "add_location >=", value, "addLocation" );
			return this;
		}


		public Criteria andAddLocationLessThan( String value ) {

			addCriterion( "add_location <", value, "addLocation" );
			return this;
		}


		public Criteria andAddLocationLessThanOrEqualTo( String value ) {

			addCriterion( "add_location <=", value, "addLocation" );
			return this;
		}


		public Criteria andAddLocationLike( String value ) {

			addCriterion( "add_location like", value, "addLocation" );
			return this;
		}


		public Criteria andAddLocationNotLike( String value ) {

			addCriterion( "add_location not like", value, "addLocation" );
			return this;
		}


		public Criteria andAddLocationIn( List values ) {

			addCriterion( "add_location in", values, "addLocation" );
			return this;
		}


		public Criteria andAddLocationNotIn( List values ) {

			addCriterion( "add_location not in", values, "addLocation" );
			return this;
		}


		public Criteria andAddLocationBetween( String value1, String value2 ) {

			addCriterion( "add_location between", value1, value2, "addLocation" );
			return this;
		}


		public Criteria andAddLocationNotBetween( String value1, String value2 ) {

			addCriterion( "add_location not between", value1, value2, "addLocation" );
			return this;
		}


		public Criteria andEditTimeIsNull() {

			addCriterion( "edit_time is null" );
			return this;
		}


		public Criteria andEditTimeIsNotNull() {

			addCriterion( "edit_time is not null" );
			return this;
		}


		public Criteria andEditTimeEqualTo( Date value ) {

			addCriterion( "edit_time =", value, "editTime" );
			return this;
		}


		public Criteria andEditTimeNotEqualTo( Date value ) {

			addCriterion( "edit_time <>", value, "editTime" );
			return this;
		}


		public Criteria andEditTimeGreaterThan( Date value ) {

			addCriterion( "edit_time >", value, "editTime" );
			return this;
		}


		public Criteria andEditTimeGreaterThanOrEqualTo( Date value ) {

			addCriterion( "edit_time >=", value, "editTime" );
			return this;
		}


		public Criteria andEditTimeLessThan( Date value ) {

			addCriterion( "edit_time <", value, "editTime" );
			return this;
		}


		public Criteria andEditTimeLessThanOrEqualTo( Date value ) {

			addCriterion( "edit_time <=", value, "editTime" );
			return this;
		}


		public Criteria andEditTimeIn( List values ) {

			addCriterion( "edit_time in", values, "editTime" );
			return this;
		}


		public Criteria andEditTimeNotIn( List values ) {

			addCriterion( "edit_time not in", values, "editTime" );
			return this;
		}


		public Criteria andEditTimeBetween( Date value1, Date value2 ) {

			addCriterion( "edit_time between", value1, value2, "editTime" );
			return this;
		}


		public Criteria andEditTimeNotBetween( Date value1, Date value2 ) {

			addCriterion( "edit_time not between", value1, value2, "editTime" );
			return this;
		}


		public Criteria andEditLocationIsNull() {

			addCriterion( "edit_location is null" );
			return this;
		}


		public Criteria andEditLocationIsNotNull() {

			addCriterion( "edit_location is not null" );
			return this;
		}


		public Criteria andEditLocationEqualTo( String value ) {

			addCriterion( "edit_location =", value, "editLocation" );
			return this;
		}


		public Criteria andEditLocationNotEqualTo( String value ) {

			addCriterion( "edit_location <>", value, "editLocation" );
			return this;
		}


		public Criteria andEditLocationGreaterThan( String value ) {

			addCriterion( "edit_location >", value, "editLocation" );
			return this;
		}


		public Criteria andEditLocationGreaterThanOrEqualTo( String value ) {

			addCriterion( "edit_location >=", value, "editLocation" );
			return this;
		}


		public Criteria andEditLocationLessThan( String value ) {

			addCriterion( "edit_location <", value, "editLocation" );
			return this;
		}


		public Criteria andEditLocationLessThanOrEqualTo( String value ) {

			addCriterion( "edit_location <=", value, "editLocation" );
			return this;
		}


		public Criteria andEditLocationLike( String value ) {

			addCriterion( "edit_location like", value, "editLocation" );
			return this;
		}


		public Criteria andEditLocationNotLike( String value ) {

			addCriterion( "edit_location not like", value, "editLocation" );
			return this;
		}


		public Criteria andEditLocationIn( List values ) {

			addCriterion( "edit_location in", values, "editLocation" );
			return this;
		}


		public Criteria andEditLocationNotIn( List values ) {

			addCriterion( "edit_location not in", values, "editLocation" );
			return this;
		}


		public Criteria andEditLocationBetween( String value1, String value2 ) {

			addCriterion( "edit_location between", value1, value2, "editLocation" );
			return this;
		}


		public Criteria andEditLocationNotBetween( String value1, String value2 ) {

			addCriterion( "edit_location not between", value1, value2, "editLocation" );
			return this;
		}


		public Criteria andLastLoginLocationIsNull() {

			addCriterion( "last_login_location is null" );
			return this;
		}


		public Criteria andLastLoginLocationIsNotNull() {

			addCriterion( "last_login_location is not null" );
			return this;
		}


		public Criteria andLastLoginLocationEqualTo( String value ) {

			addCriterion( "last_login_location =", value, "lastLoginLocation" );
			return this;
		}


		public Criteria andLastLoginLocationNotEqualTo( String value ) {

			addCriterion( "last_login_location <>", value, "lastLoginLocation" );
			return this;
		}


		public Criteria andLastLoginLocationGreaterThan( String value ) {

			addCriterion( "last_login_location >", value, "lastLoginLocation" );
			return this;
		}


		public Criteria andLastLoginLocationGreaterThanOrEqualTo( String value ) {

			addCriterion( "last_login_location >=", value, "lastLoginLocation" );
			return this;
		}


		public Criteria andLastLoginLocationLessThan( String value ) {

			addCriterion( "last_login_location <", value, "lastLoginLocation" );
			return this;
		}


		public Criteria andLastLoginLocationLessThanOrEqualTo( String value ) {

			addCriterion( "last_login_location <=", value, "lastLoginLocation" );
			return this;
		}


		public Criteria andLastLoginLocationLike( String value ) {

			addCriterion( "last_login_location like", value, "lastLoginLocation" );
			return this;
		}


		public Criteria andLastLoginLocationNotLike( String value ) {

			addCriterion( "last_login_location not like", value, "lastLoginLocation" );
			return this;
		}


		public Criteria andLastLoginLocationIn( List values ) {

			addCriterion( "last_login_location in", values, "lastLoginLocation" );
			return this;
		}


		public Criteria andLastLoginLocationNotIn( List values ) {

			addCriterion( "last_login_location not in", values, "lastLoginLocation" );
			return this;
		}


		public Criteria andLastLoginLocationBetween( String value1, String value2 ) {

			addCriterion( "last_login_location between", value1, value2, "lastLoginLocation" );
			return this;
		}


		public Criteria andLastLoginLocationNotBetween( String value1, String value2 ) {

			addCriterion( "last_login_location not between", value1, value2, "lastLoginLocation" );
			return this;
		}


		public Criteria andFriendsIsNull() {

			addCriterion( "friends is null" );
			return this;
		}


		public Criteria andFriendsIsNotNull() {

			addCriterion( "friends is not null" );
			return this;
		}


		public Criteria andFriendsEqualTo( String value ) {

			addCriterion( "friends =", value, "friends" );
			return this;
		}


		public Criteria andFriendsNotEqualTo( String value ) {

			addCriterion( "friends <>", value, "friends" );
			return this;
		}


		public Criteria andFriendsGreaterThan( String value ) {

			addCriterion( "friends >", value, "friends" );
			return this;
		}


		public Criteria andFriendsGreaterThanOrEqualTo( String value ) {

			addCriterion( "friends >=", value, "friends" );
			return this;
		}


		public Criteria andFriendsLessThan( String value ) {

			addCriterion( "friends <", value, "friends" );
			return this;
		}


		public Criteria andFriendsLessThanOrEqualTo( String value ) {

			addCriterion( "friends <=", value, "friends" );
			return this;
		}


		public Criteria andFriendsLike( String value ) {

			addCriterion( "friends like", value, "friends" );
			return this;
		}


		public Criteria andFriendsNotLike( String value ) {

			addCriterion( "friends not like", value, "friends" );
			return this;
		}


		public Criteria andFriendsIn( List values ) {

			addCriterion( "friends in", values, "friends" );
			return this;
		}


		public Criteria andFriendsNotIn( List values ) {

			addCriterion( "friends not in", values, "friends" );
			return this;
		}


		public Criteria andFriendsBetween( String value1, String value2 ) {

			addCriterion( "friends between", value1, value2, "friends" );
			return this;
		}


		public Criteria andFriendsNotBetween( String value1, String value2 ) {

			addCriterion( "friends not between", value1, value2, "friends" );
			return this;
		}


		public Criteria andCityIsNull() {

			addCriterion( "city is null" );
			return this;
		}


		public Criteria andCityIsNotNull() {

			addCriterion( "city is not null" );
			return this;
		}


		public Criteria andCityEqualTo( String value ) {

			addCriterion( "city =", value, "city" );
			return this;
		}


		public Criteria andCityNotEqualTo( String value ) {

			addCriterion( "city <>", value, "city" );
			return this;
		}


		public Criteria andCityGreaterThan( String value ) {

			addCriterion( "city >", value, "city" );
			return this;
		}


		public Criteria andCityGreaterThanOrEqualTo( String value ) {

			addCriterion( "city >=", value, "city" );
			return this;
		}


		public Criteria andCityLessThan( String value ) {

			addCriterion( "city <", value, "city" );
			return this;
		}


		public Criteria andCityLessThanOrEqualTo( String value ) {

			addCriterion( "city <=", value, "city" );
			return this;
		}


		public Criteria andCityLike( String value ) {

			addCriterion( "city like", value, "city" );
			return this;
		}


		public Criteria andCityNotLike( String value ) {

			addCriterion( "city not like", value, "city" );
			return this;
		}


		public Criteria andCityIn( List values ) {

			addCriterion( "city in", values, "city" );
			return this;
		}


		public Criteria andCityNotIn( List values ) {

			addCriterion( "city not in", values, "city" );
			return this;
		}


		public Criteria andCityBetween( String value1, String value2 ) {

			addCriterion( "city between", value1, value2, "city" );
			return this;
		}


		public Criteria andCityNotBetween( String value1, String value2 ) {

			addCriterion( "city not between", value1, value2, "city" );
			return this;
		}


		public Criteria andPhoneIsNull() {

			addCriterion( "phone is null" );
			return this;
		}


		public Criteria andPhoneIsNotNull() {

			addCriterion( "phone is not null" );
			return this;
		}


		public Criteria andPhoneEqualTo( String value ) {

			addCriterion( "phone =", value, "phone" );
			return this;
		}


		public Criteria andPhoneNotEqualTo( String value ) {

			addCriterion( "phone <>", value, "phone" );
			return this;
		}


		public Criteria andPhoneGreaterThan( String value ) {

			addCriterion( "phone >", value, "phone" );
			return this;
		}


		public Criteria andPhoneGreaterThanOrEqualTo( String value ) {

			addCriterion( "phone >=", value, "phone" );
			return this;
		}


		public Criteria andPhoneLessThan( String value ) {

			addCriterion( "phone <", value, "phone" );
			return this;
		}


		public Criteria andPhoneLessThanOrEqualTo( String value ) {

			addCriterion( "phone <=", value, "phone" );
			return this;
		}


		public Criteria andPhoneLike( String value ) {

			addCriterion( "phone like", value, "phone" );
			return this;
		}


		public Criteria andPhoneNotLike( String value ) {

			addCriterion( "phone not like", value, "phone" );
			return this;
		}


		public Criteria andPhoneIn( List values ) {

			addCriterion( "phone in", values, "phone" );
			return this;
		}


		public Criteria andPhoneNotIn( List values ) {

			addCriterion( "phone not in", values, "phone" );
			return this;
		}


		public Criteria andPhoneBetween( String value1, String value2 ) {

			addCriterion( "phone between", value1, value2, "phone" );
			return this;
		}


		public Criteria andPhoneNotBetween( String value1, String value2 ) {

			addCriterion( "phone not between", value1, value2, "phone" );
			return this;
		}
	}
}