package com.linklife.domain.ibator;

import java.util.Date;

import com.linklife.domain.base.BaseDomain;
import com.linklife.repository.base.SqlMap;

/**
 * <p>
 * AccountInfo.java
 * </p>
 * 
 * <pre>
 * 用户信息表对应实体类
 * </pre>
 * 
 * @author caisupeng
 */
@SqlMap(Name = "account_info", Class = AccountInfo.class)
public class AccountInfo<T, U> extends BaseDomain<T, U>{

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column account_info.account_id
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	private Integer accountId;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column account_info.name
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	private String name;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column account_info.birthday
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	private Date birthday;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column account_info.authority
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	private String authority;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column account_info.add_time
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	private Date addTime;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column account_info.add_location
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	private String addLocation;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column account_info.edit_time
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	private Date editTime;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column account_info.edit_location
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	private String editLocation;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column account_info.last_login_location
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	private String lastLoginLocation;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column account_info.friends
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	private String friends;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column account_info.city
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	private String city;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column account_info.phone
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	private String phone;
	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column account_info.account_id
	 * @return  the value of account_info.account_id
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public Integer getAccountId() {

		return accountId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column account_info.account_id
	 * @param accountId  the value for account_info.account_id
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public void setAccountId( Integer accountId ) {

		this.accountId = accountId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column account_info.name
	 * @return  the value of account_info.name
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public String getName() {

		return name;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column account_info.name
	 * @param name  the value for account_info.name
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public void setName( String name ) {

		this.name = name;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column account_info.birthday
	 * @return  the value of account_info.birthday
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public Date getBirthday() {

		return birthday;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column account_info.birthday
	 * @param birthday  the value for account_info.birthday
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public void setBirthday( Date birthday ) {

		this.birthday = birthday;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column account_info.authority
	 * @return  the value of account_info.authority
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public String getAuthority() {

		return authority;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column account_info.authority
	 * @param authority  the value for account_info.authority
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public void setAuthority( String authority ) {

		this.authority = authority;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column account_info.add_time
	 * @return  the value of account_info.add_time
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public Date getAddTime() {

		return addTime;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column account_info.add_time
	 * @param addTime  the value for account_info.add_time
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public void setAddTime( Date addTime ) {

		this.addTime = addTime;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column account_info.add_location
	 * @return  the value of account_info.add_location
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public String getAddLocation() {

		return addLocation;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column account_info.add_location
	 * @param addLocation  the value for account_info.add_location
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public void setAddLocation( String addLocation ) {

		this.addLocation = addLocation;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column account_info.edit_time
	 * @return  the value of account_info.edit_time
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public Date getEditTime() {

		return editTime;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column account_info.edit_time
	 * @param editTime  the value for account_info.edit_time
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public void setEditTime( Date editTime ) {

		this.editTime = editTime;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column account_info.edit_location
	 * @return  the value of account_info.edit_location
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public String getEditLocation() {

		return editLocation;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column account_info.edit_location
	 * @param editLocation  the value for account_info.edit_location
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public void setEditLocation( String editLocation ) {

		this.editLocation = editLocation;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column account_info.last_login_location
	 * @return  the value of account_info.last_login_location
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public String getLastLoginLocation() {

		return lastLoginLocation;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column account_info.last_login_location
	 * @param lastLoginLocation  the value for account_info.last_login_location
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public void setLastLoginLocation( String lastLoginLocation ) {

		this.lastLoginLocation = lastLoginLocation;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column account_info.friends
	 * @return  the value of account_info.friends
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public String getFriends() {

		return friends;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column account_info.friends
	 * @param friends  the value for account_info.friends
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public void setFriends( String friends ) {

		this.friends = friends;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column account_info.city
	 * @return  the value of account_info.city
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public String getCity() {

		return city;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column account_info.city
	 * @param city  the value for account_info.city
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public void setCity( String city ) {

		this.city = city;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column account_info.phone
	 * @return  the value of account_info.phone
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public String getPhone() {

		return phone;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column account_info.phone
	 * @param phone  the value for account_info.phone
	 * @ibatorgenerated  Sat Jan 03 16:09:10 CST 2015
	 */
	public void setPhone( String phone ) {

		this.phone = phone;
	}

	
}