package com.linklife.domain.ibator;

import com.linklife.domain.base.BaseDomain;
import com.linklife.repository.base.SqlMap;

/**
 * <p>
 * AccountInfo.java
 * </p>
 * 
 * <pre>
 * 用户登录表对应实体类
 * </pre>
 * 
 * @author caisupeng
 */
@SqlMap(Name = "account_login", Class = AccountLogin.class)
public class AccountLogin<T, U> extends BaseDomain<T, U> {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column account_login.account_id
     *
     * @ibatorgenerated Fri Aug 01 15:13:54 CST 2014
     */
    private Integer accountId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column account_login.email
     *
     * @ibatorgenerated Fri Aug 01 15:13:54 CST 2014
     */
    private String email;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column account_login.password
     *
     * @ibatorgenerated Fri Aug 01 15:13:54 CST 2014
     */
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column account_login.status
     *
     * @ibatorgenerated Fri Aug 01 15:13:54 CST 2014
     */
    private Byte status;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column account_login.account_id
     *
     * @return the value of account_login.account_id
     *
     * @ibatorgenerated Fri Aug 01 15:13:54 CST 2014
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column account_login.account_id
     *
     * @param accountId the value for account_login.account_id
     *
     * @ibatorgenerated Fri Aug 01 15:13:54 CST 2014
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column account_login.email
     *
     * @return the value of account_login.email
     *
     * @ibatorgenerated Fri Aug 01 15:13:54 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column account_login.email
     *
     * @param email the value for account_login.email
     *
     * @ibatorgenerated Fri Aug 01 15:13:54 CST 2014
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column account_login.password
     *
     * @return the value of account_login.password
     *
     * @ibatorgenerated Fri Aug 01 15:13:54 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column account_login.password
     *
     * @param password the value for account_login.password
     *
     * @ibatorgenerated Fri Aug 01 15:13:54 CST 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column account_login.status
     *
     * @return the value of account_login.status
     *
     * @ibatorgenerated Fri Aug 01 15:13:54 CST 2014
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column account_login.status
     *
     * @param status the value for account_login.status
     *
     * @ibatorgenerated Fri Aug 01 15:13:54 CST 2014
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}