package com.linklife.domain.ibator;

import com.linklife.domain.base.BaseDomain;
import com.linklife.repository.base.SqlMap;

@SqlMap( Name = "daily_check_account", Class = DailyCheckAccount.class )
public class DailyCheckAccount<T, U> extends BaseDomain<T, U> {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column daily_check_account.id
	 *
	 * @ibatorgenerated Wed Jun 03 21:04:57 CST 2015
	 */
	private Integer id;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column daily_check_account.account
	 *
	 * @ibatorgenerated Wed Jun 03 21:04:57 CST 2015
	 */
	private String account;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column daily_check_account.name
	 *
	 * @ibatorgenerated Wed Jun 03 21:04:57 CST 2015
	 */
	private String name;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column daily_check_account.password
	 *
	 * @ibatorgenerated Wed Jun 03 21:04:57 CST 2015
	 */
	private String password;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column daily_check_account.state
	 *
	 * @ibatorgenerated Wed Jun 03 21:04:57 CST 2015
	 */
	private Integer state;


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column daily_check_account.id
	 *
	 * @return the value of daily_check_account.id
	 *
	 * @ibatorgenerated Wed Jun 03 21:04:57 CST 2015
	 */
	public Integer getId() {

		return id;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column daily_check_account.id
	 *
	 * @param id
	 *            the value for daily_check_account.id
	 *
	 * @ibatorgenerated Wed Jun 03 21:04:57 CST 2015
	 */
	public void setId( Integer id ) {

		this.id = id;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column daily_check_account.account
	 *
	 * @return the value of daily_check_account.account
	 *
	 * @ibatorgenerated Wed Jun 03 21:04:57 CST 2015
	 */
	public String getAccount() {

		return account;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column daily_check_account.account
	 *
	 * @param account
	 *            the value for daily_check_account.account
	 *
	 * @ibatorgenerated Wed Jun 03 21:04:57 CST 2015
	 */
	public void setAccount( String account ) {

		this.account = account;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column daily_check_account.name
	 *
	 * @return the value of daily_check_account.name
	 *
	 * @ibatorgenerated Wed Jun 03 21:04:57 CST 2015
	 */
	public String getName() {

		return name;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column daily_check_account.name
	 *
	 * @param name
	 *            the value for daily_check_account.name
	 *
	 * @ibatorgenerated Wed Jun 03 21:04:57 CST 2015
	 */
	public void setName( String name ) {

		this.name = name;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column daily_check_account.password
	 *
	 * @return the value of daily_check_account.password
	 *
	 * @ibatorgenerated Wed Jun 03 21:04:57 CST 2015
	 */
	public String getPassword() {

		return password;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column daily_check_account.password
	 *
	 * @param password
	 *            the value for daily_check_account.password
	 *
	 * @ibatorgenerated Wed Jun 03 21:04:57 CST 2015
	 */
	public void setPassword( String password ) {

		this.password = password;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column daily_check_account.state
	 *
	 * @return the value of daily_check_account.state
	 *
	 * @ibatorgenerated Wed Jun 03 21:04:57 CST 2015
	 */
	public Integer getState() {

		return state;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column daily_check_account.state
	 *
	 * @param state
	 *            the value for daily_check_account.state
	 *
	 * @ibatorgenerated Wed Jun 03 21:04:57 CST 2015
	 */
	public void setState( Integer state ) {

		this.state = state;
	}
}