package com.linklife.domain.ibator;

import java.util.Date;

import com.linklife.domain.base.BaseDomain;
import com.linklife.repository.base.SqlMap;

@SqlMap( Name = "daily_check_update", Class = DailyCheckUpdate.class )
public class DailyCheckUpdate<T, U> extends BaseDomain<T, U>  {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_check_update.id
     *
     * @ibatorgenerated Wed Jun 03 21:06:52 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_check_update.type
     *
     * @ibatorgenerated Wed Jun 03 21:06:52 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_check_update.content
     *
     * @ibatorgenerated Wed Jun 03 21:06:52 CST 2015
     */
    private String content;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_check_update.data
     *
     * @ibatorgenerated Wed Jun 03 21:06:52 CST 2015
     */
    private Date data;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_check_update.id
     *
     * @return the value of daily_check_update.id
     *
     * @ibatorgenerated Wed Jun 03 21:06:52 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_check_update.id
     *
     * @param id the value for daily_check_update.id
     *
     * @ibatorgenerated Wed Jun 03 21:06:52 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_check_update.type
     *
     * @return the value of daily_check_update.type
     *
     * @ibatorgenerated Wed Jun 03 21:06:52 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_check_update.type
     *
     * @param type the value for daily_check_update.type
     *
     * @ibatorgenerated Wed Jun 03 21:06:52 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_check_update.content
     *
     * @return the value of daily_check_update.content
     *
     * @ibatorgenerated Wed Jun 03 21:06:52 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_check_update.content
     *
     * @param content the value for daily_check_update.content
     *
     * @ibatorgenerated Wed Jun 03 21:06:52 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_check_update.data
     *
     * @return the value of daily_check_update.data
     *
     * @ibatorgenerated Wed Jun 03 21:06:52 CST 2015
     */
    public Date getData() {
        return data;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_check_update.data
     *
     * @param data the value for daily_check_update.data
     *
     * @ibatorgenerated Wed Jun 03 21:06:52 CST 2015
     */
    public void setData(Date data) {
        this.data = data;
    }
}