package com.linklife.domain.ibator;

import java.util.Date;

import com.linklife.domain.base.BaseDomain;
import com.linklife.repository.base.SqlMap;

@SqlMap( Name = "daily_check_issues", Class = DailyCheckIssues.class )
public class DailyCheckIssues<T, U> extends BaseDomain<T, U> {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column daily_check_issues.id
	 *
	 * @ibatorgenerated Wed Jun 03 21:05:26 CST 2015
	 */
	private Integer id;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column daily_check_issues.solved
	 *
	 * @ibatorgenerated Wed Jun 03 21:05:26 CST 2015
	 */
	private Integer solved;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column daily_check_issues.onhand
	 *
	 * @ibatorgenerated Wed Jun 03 21:05:26 CST 2015
	 */
	private Integer onhand;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column daily_check_issues.data
	 *
	 * @ibatorgenerated Wed Jun 03 21:05:26 CST 2015
	 */
	private Date data;


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column daily_check_issues.id
	 *
	 * @return the value of daily_check_issues.id
	 *
	 * @ibatorgenerated Wed Jun 03 21:05:26 CST 2015
	 */
	public Integer getId() {

		return id;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column daily_check_issues.id
	 *
	 * @param id
	 *            the value for daily_check_issues.id
	 *
	 * @ibatorgenerated Wed Jun 03 21:05:26 CST 2015
	 */
	public void setId( Integer id ) {

		this.id = id;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column daily_check_issues.solved
	 *
	 * @return the value of daily_check_issues.solved
	 *
	 * @ibatorgenerated Wed Jun 03 21:05:26 CST 2015
	 */
	public Integer getSolved() {

		return solved;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column daily_check_issues.solved
	 *
	 * @param solved
	 *            the value for daily_check_issues.solved
	 *
	 * @ibatorgenerated Wed Jun 03 21:05:26 CST 2015
	 */
	public void setSolved( Integer solved ) {

		this.solved = solved;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column daily_check_issues.onhand
	 *
	 * @return the value of daily_check_issues.onhand
	 *
	 * @ibatorgenerated Wed Jun 03 21:05:26 CST 2015
	 */
	public Integer getOnhand() {

		return onhand;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column daily_check_issues.onhand
	 *
	 * @param onhand
	 *            the value for daily_check_issues.onhand
	 *
	 * @ibatorgenerated Wed Jun 03 21:05:26 CST 2015
	 */
	public void setOnhand( Integer onhand ) {

		this.onhand = onhand;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column daily_check_issues.data
	 *
	 * @return the value of daily_check_issues.data
	 *
	 * @ibatorgenerated Wed Jun 03 21:05:26 CST 2015
	 */
	public Date getData() {

		return data;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column daily_check_issues.data
	 *
	 * @param data
	 *            the value for daily_check_issues.data
	 *
	 * @ibatorgenerated Wed Jun 03 21:05:26 CST 2015
	 */
	public void setData( Date data ) {

		this.data = data;
	}
}