package com.linklife.domain.ibator;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class NuistChatExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public NuistChatExample() {

		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	protected NuistChatExample( NuistChatExample example ) {

		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public void setOrderByClause( String orderByClause ) {

		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public String getOrderByClause() {

		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public List getOredCriteria() {

		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public void or( Criteria criteria ) {

		oredCriteria.add( criteria );
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public Criteria createCriteria() {

		Criteria criteria = createCriteriaInternal();
		if( oredCriteria.size() == 0 ) {
			oredCriteria.add( criteria );
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	protected Criteria createCriteriaInternal() {

		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public void clear() {

		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table nuist_chat
	 * @ibatorgenerated  Sat Jul 25 22:12:25 CST 2015
	 */
	public static class Criteria {

		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;


		protected Criteria() {

			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}


		public boolean isValid() {

			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}


		public List getCriteriaWithoutValue() {

			return criteriaWithoutValue;
		}


		public List getCriteriaWithSingleValue() {

			return criteriaWithSingleValue;
		}


		public List getCriteriaWithListValue() {

			return criteriaWithListValue;
		}


		public List getCriteriaWithBetweenValue() {

			return criteriaWithBetweenValue;
		}


		protected void addCriterion( String condition ) {

			if( condition == null ) {
				throw new RuntimeException( "Value for condition cannot be null" );
			}
			criteriaWithoutValue.add( condition );
		}


		protected void addCriterion( String condition, Object value, String property ) {

			if( value == null ) {
				throw new RuntimeException( "Value for " + property + " cannot be null" );
			}
			Map map = new HashMap();
			map.put( "condition", condition );
			map.put( "value", value );
			criteriaWithSingleValue.add( map );
		}


		protected void addCriterion( String condition, List values, String property ) {

			if( values == null || values.size() == 0 ) {
				throw new RuntimeException( "Value list for " + property + " cannot be null or empty" );
			}
			Map map = new HashMap();
			map.put( "condition", condition );
			map.put( "values", values );
			criteriaWithListValue.add( map );
		}


		protected void addCriterion( String condition, Object value1, Object value2, String property ) {

			if( value1 == null || value2 == null ) {
				throw new RuntimeException( "Between values for " + property + " cannot be null" );
			}
			List list = new ArrayList();
			list.add( value1 );
			list.add( value2 );
			Map map = new HashMap();
			map.put( "condition", condition );
			map.put( "values", list );
			criteriaWithBetweenValue.add( map );
		}


		public Criteria andChatIdIsNull() {

			addCriterion( "chat_id is null" );
			return this;
		}


		public Criteria andChatIdIsNotNull() {

			addCriterion( "chat_id is not null" );
			return this;
		}


		public Criteria andChatIdEqualTo( Integer value ) {

			addCriterion( "chat_id =", value, "chatId" );
			return this;
		}


		public Criteria andChatIdNotEqualTo( Integer value ) {

			addCriterion( "chat_id <>", value, "chatId" );
			return this;
		}


		public Criteria andChatIdGreaterThan( Integer value ) {

			addCriterion( "chat_id >", value, "chatId" );
			return this;
		}


		public Criteria andChatIdGreaterThanOrEqualTo( Integer value ) {

			addCriterion( "chat_id >=", value, "chatId" );
			return this;
		}


		public Criteria andChatIdLessThan( Integer value ) {

			addCriterion( "chat_id <", value, "chatId" );
			return this;
		}


		public Criteria andChatIdLessThanOrEqualTo( Integer value ) {

			addCriterion( "chat_id <=", value, "chatId" );
			return this;
		}


		public Criteria andChatIdIn( List values ) {

			addCriterion( "chat_id in", values, "chatId" );
			return this;
		}


		public Criteria andChatIdNotIn( List values ) {

			addCriterion( "chat_id not in", values, "chatId" );
			return this;
		}


		public Criteria andChatIdBetween( Integer value1, Integer value2 ) {

			addCriterion( "chat_id between", value1, value2, "chatId" );
			return this;
		}


		public Criteria andChatIdNotBetween( Integer value1, Integer value2 ) {

			addCriterion( "chat_id not between", value1, value2, "chatId" );
			return this;
		}


		public Criteria andAccountIdIsNull() {

			addCriterion( "account_id is null" );
			return this;
		}


		public Criteria andAccountIdIsNotNull() {

			addCriterion( "account_id is not null" );
			return this;
		}


		public Criteria andAccountIdEqualTo( Integer value ) {

			addCriterion( "account_id =", value, "accountId" );
			return this;
		}


		public Criteria andAccountIdNotEqualTo( Integer value ) {

			addCriterion( "account_id <>", value, "accountId" );
			return this;
		}


		public Criteria andAccountIdGreaterThan( Integer value ) {

			addCriterion( "account_id >", value, "accountId" );
			return this;
		}


		public Criteria andAccountIdGreaterThanOrEqualTo( Integer value ) {

			addCriterion( "account_id >=", value, "accountId" );
			return this;
		}


		public Criteria andAccountIdLessThan( Integer value ) {

			addCriterion( "account_id <", value, "accountId" );
			return this;
		}


		public Criteria andAccountIdLessThanOrEqualTo( Integer value ) {

			addCriterion( "account_id <=", value, "accountId" );
			return this;
		}


		public Criteria andAccountIdIn( List values ) {

			addCriterion( "account_id in", values, "accountId" );
			return this;
		}


		public Criteria andAccountIdNotIn( List values ) {

			addCriterion( "account_id not in", values, "accountId" );
			return this;
		}


		public Criteria andAccountIdBetween( Integer value1, Integer value2 ) {

			addCriterion( "account_id between", value1, value2, "accountId" );
			return this;
		}


		public Criteria andAccountIdNotBetween( Integer value1, Integer value2 ) {

			addCriterion( "account_id not between", value1, value2, "accountId" );
			return this;
		}


		public Criteria andUsernameIsNull() {

			addCriterion( "username is null" );
			return this;
		}


		public Criteria andUsernameIsNotNull() {

			addCriterion( "username is not null" );
			return this;
		}


		public Criteria andUsernameEqualTo( String value ) {

			addCriterion( "username =", value, "username" );
			return this;
		}


		public Criteria andUsernameNotEqualTo( String value ) {

			addCriterion( "username <>", value, "username" );
			return this;
		}


		public Criteria andUsernameGreaterThan( String value ) {

			addCriterion( "username >", value, "username" );
			return this;
		}


		public Criteria andUsernameGreaterThanOrEqualTo( String value ) {

			addCriterion( "username >=", value, "username" );
			return this;
		}


		public Criteria andUsernameLessThan( String value ) {

			addCriterion( "username <", value, "username" );
			return this;
		}


		public Criteria andUsernameLessThanOrEqualTo( String value ) {

			addCriterion( "username <=", value, "username" );
			return this;
		}


		public Criteria andUsernameLike( String value ) {

			addCriterion( "username like", value, "username" );
			return this;
		}


		public Criteria andUsernameNotLike( String value ) {

			addCriterion( "username not like", value, "username" );
			return this;
		}


		public Criteria andUsernameIn( List values ) {

			addCriterion( "username in", values, "username" );
			return this;
		}


		public Criteria andUsernameNotIn( List values ) {

			addCriterion( "username not in", values, "username" );
			return this;
		}


		public Criteria andUsernameBetween( String value1, String value2 ) {

			addCriterion( "username between", value1, value2, "username" );
			return this;
		}


		public Criteria andUsernameNotBetween( String value1, String value2 ) {

			addCriterion( "username not between", value1, value2, "username" );
			return this;
		}


		public Criteria andClassIdIsNull() {

			addCriterion( "class_id is null" );
			return this;
		}


		public Criteria andClassIdIsNotNull() {

			addCriterion( "class_id is not null" );
			return this;
		}


		public Criteria andClassIdEqualTo( Integer value ) {

			addCriterion( "class_id =", value, "classId" );
			return this;
		}


		public Criteria andClassIdNotEqualTo( Integer value ) {

			addCriterion( "class_id <>", value, "classId" );
			return this;
		}


		public Criteria andClassIdGreaterThan( Integer value ) {

			addCriterion( "class_id >", value, "classId" );
			return this;
		}


		public Criteria andClassIdGreaterThanOrEqualTo( Integer value ) {

			addCriterion( "class_id >=", value, "classId" );
			return this;
		}


		public Criteria andClassIdLessThan( Integer value ) {

			addCriterion( "class_id <", value, "classId" );
			return this;
		}


		public Criteria andClassIdLessThanOrEqualTo( Integer value ) {

			addCriterion( "class_id <=", value, "classId" );
			return this;
		}


		public Criteria andClassIdIn( List values ) {

			addCriterion( "class_id in", values, "classId" );
			return this;
		}


		public Criteria andClassIdNotIn( List values ) {

			addCriterion( "class_id not in", values, "classId" );
			return this;
		}


		public Criteria andClassIdBetween( Integer value1, Integer value2 ) {

			addCriterion( "class_id between", value1, value2, "classId" );
			return this;
		}


		public Criteria andClassIdNotBetween( Integer value1, Integer value2 ) {

			addCriterion( "class_id not between", value1, value2, "classId" );
			return this;
		}


		public Criteria andParentIdIsNull() {

			addCriterion( "parent_id is null" );
			return this;
		}


		public Criteria andParentIdIsNotNull() {

			addCriterion( "parent_id is not null" );
			return this;
		}


		public Criteria andParentIdEqualTo( Integer value ) {

			addCriterion( "parent_id =", value, "parentId" );
			return this;
		}


		public Criteria andParentIdNotEqualTo( Integer value ) {

			addCriterion( "parent_id <>", value, "parentId" );
			return this;
		}


		public Criteria andParentIdGreaterThan( Integer value ) {

			addCriterion( "parent_id >", value, "parentId" );
			return this;
		}


		public Criteria andParentIdGreaterThanOrEqualTo( Integer value ) {

			addCriterion( "parent_id >=", value, "parentId" );
			return this;
		}


		public Criteria andParentIdLessThan( Integer value ) {

			addCriterion( "parent_id <", value, "parentId" );
			return this;
		}


		public Criteria andParentIdLessThanOrEqualTo( Integer value ) {

			addCriterion( "parent_id <=", value, "parentId" );
			return this;
		}


		public Criteria andParentIdIn( List values ) {

			addCriterion( "parent_id in", values, "parentId" );
			return this;
		}


		public Criteria andParentIdNotIn( List values ) {

			addCriterion( "parent_id not in", values, "parentId" );
			return this;
		}


		public Criteria andParentIdBetween( Integer value1, Integer value2 ) {

			addCriterion( "parent_id between", value1, value2, "parentId" );
			return this;
		}


		public Criteria andParentIdNotBetween( Integer value1, Integer value2 ) {

			addCriterion( "parent_id not between", value1, value2, "parentId" );
			return this;
		}


		public Criteria andContentIsNull() {

			addCriterion( "content is null" );
			return this;
		}


		public Criteria andContentIsNotNull() {

			addCriterion( "content is not null" );
			return this;
		}


		public Criteria andContentEqualTo( String value ) {

			addCriterion( "content =", value, "content" );
			return this;
		}


		public Criteria andContentNotEqualTo( String value ) {

			addCriterion( "content <>", value, "content" );
			return this;
		}


		public Criteria andContentGreaterThan( String value ) {

			addCriterion( "content >", value, "content" );
			return this;
		}


		public Criteria andContentGreaterThanOrEqualTo( String value ) {

			addCriterion( "content >=", value, "content" );
			return this;
		}


		public Criteria andContentLessThan( String value ) {

			addCriterion( "content <", value, "content" );
			return this;
		}


		public Criteria andContentLessThanOrEqualTo( String value ) {

			addCriterion( "content <=", value, "content" );
			return this;
		}


		public Criteria andContentLike( String value ) {

			addCriterion( "content like", value, "content" );
			return this;
		}


		public Criteria andContentNotLike( String value ) {

			addCriterion( "content not like", value, "content" );
			return this;
		}


		public Criteria andContentIn( List values ) {

			addCriterion( "content in", values, "content" );
			return this;
		}


		public Criteria andContentNotIn( List values ) {

			addCriterion( "content not in", values, "content" );
			return this;
		}


		public Criteria andContentBetween( String value1, String value2 ) {

			addCriterion( "content between", value1, value2, "content" );
			return this;
		}


		public Criteria andContentNotBetween( String value1, String value2 ) {

			addCriterion( "content not between", value1, value2, "content" );
			return this;
		}


		public Criteria andAddTimeIsNull() {

			addCriterion( "add_time is null" );
			return this;
		}


		public Criteria andAddTimeIsNotNull() {

			addCriterion( "add_time is not null" );
			return this;
		}


		public Criteria andAddTimeEqualTo( Date value ) {

			addCriterion( "add_time =", value, "addTime" );
			return this;
		}


		public Criteria andAddTimeNotEqualTo( Date value ) {

			addCriterion( "add_time <>", value, "addTime" );
			return this;
		}


		public Criteria andAddTimeGreaterThan( Date value ) {

			addCriterion( "add_time >", value, "addTime" );
			return this;
		}


		public Criteria andAddTimeGreaterThanOrEqualTo( Date value ) {

			addCriterion( "add_time >=", value, "addTime" );
			return this;
		}


		public Criteria andAddTimeLessThan( Date value ) {

			addCriterion( "add_time <", value, "addTime" );
			return this;
		}


		public Criteria andAddTimeLessThanOrEqualTo( Date value ) {

			addCriterion( "add_time <=", value, "addTime" );
			return this;
		}


		public Criteria andAddTimeIn( List values ) {

			addCriterion( "add_time in", values, "addTime" );
			return this;
		}


		public Criteria andAddTimeNotIn( List values ) {

			addCriterion( "add_time not in", values, "addTime" );
			return this;
		}


		public Criteria andAddTimeBetween( Date value1, Date value2 ) {

			addCriterion( "add_time between", value1, value2, "addTime" );
			return this;
		}


		public Criteria andAddTimeNotBetween( Date value1, Date value2 ) {

			addCriterion( "add_time not between", value1, value2, "addTime" );
			return this;
		}


		public Criteria andAddIpIsNull() {

			addCriterion( "add_ip is null" );
			return this;
		}


		public Criteria andAddIpIsNotNull() {

			addCriterion( "add_ip is not null" );
			return this;
		}


		public Criteria andAddIpEqualTo( String value ) {

			addCriterion( "add_ip =", value, "addIp" );
			return this;
		}


		public Criteria andAddIpNotEqualTo( String value ) {

			addCriterion( "add_ip <>", value, "addIp" );
			return this;
		}


		public Criteria andAddIpGreaterThan( String value ) {

			addCriterion( "add_ip >", value, "addIp" );
			return this;
		}


		public Criteria andAddIpGreaterThanOrEqualTo( String value ) {

			addCriterion( "add_ip >=", value, "addIp" );
			return this;
		}


		public Criteria andAddIpLessThan( String value ) {

			addCriterion( "add_ip <", value, "addIp" );
			return this;
		}


		public Criteria andAddIpLessThanOrEqualTo( String value ) {

			addCriterion( "add_ip <=", value, "addIp" );
			return this;
		}


		public Criteria andAddIpLike( String value ) {

			addCriterion( "add_ip like", value, "addIp" );
			return this;
		}


		public Criteria andAddIpNotLike( String value ) {

			addCriterion( "add_ip not like", value, "addIp" );
			return this;
		}


		public Criteria andAddIpIn( List values ) {

			addCriterion( "add_ip in", values, "addIp" );
			return this;
		}


		public Criteria andAddIpNotIn( List values ) {

			addCriterion( "add_ip not in", values, "addIp" );
			return this;
		}


		public Criteria andAddIpBetween( String value1, String value2 ) {

			addCriterion( "add_ip between", value1, value2, "addIp" );
			return this;
		}


		public Criteria andAddIpNotBetween( String value1, String value2 ) {

			addCriterion( "add_ip not between", value1, value2, "addIp" );
			return this;
		}
	}
}