package com.linklife.domain.ibator;

import java.util.Date;

import com.linklife.domain.base.BaseDomain;
import com.linklife.repository.base.SqlMap;

/**
 * <p>
 * NuistRechargeHistory.java
 * </p>
 * 
 * <pre>
 * 南信大一卡�?�充值记录表对应实体�??
 * </pre>
 * 
 * @author caisupeng
 */
@SqlMap( Name = "nuist_recharge_history", Class = NuistRechargeHistory.class )
public class NuistRechargeHistory<T, U> extends BaseDomain<T, U> {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_recharge_history.recharge_id
	 * 
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	private Integer rechargeId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_recharge_history.account_id
	 * 
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	private Integer accountId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_recharge_history.recharge_amount
	 * 
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	private Double rechargeAmount;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_recharge_history.add_time
	 * 
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	private Date addTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_recharge_history.add_ip
	 * 
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	private String addIp;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_recharge_history.country
	 * 
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	private String country;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_recharge_history.country_id
	 * 
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	private String countryId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_recharge_history.area
	 * 
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	private String area;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_recharge_history.area_id
	 * 
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	private String areaId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_recharge_history.region
	 * 
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	private String region;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_recharge_history.region_id
	 * 
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	private String regionId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_recharge_history.city
	 * 
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	private String city;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_recharge_history.city_id
	 * 
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	private String cityId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_recharge_history.isp
	 * 
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	private String isp;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_recharge_history.isp_id
	 * 
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	private String ispId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_recharge_history.explorer_version
	 * 
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	private String explorerVersion;


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_recharge_history.recharge_id
	 * 
	 * @return the value of nuist_recharge_history.recharge_id
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public Integer getRechargeId() {

		return rechargeId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_recharge_history.recharge_id
	 * 
	 * @param rechargeId
	 *            the value for nuist_recharge_history.recharge_id
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public void setRechargeId( Integer rechargeId ) {

		this.rechargeId = rechargeId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_recharge_history.account_id
	 * 
	 * @return the value of nuist_recharge_history.account_id
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public Integer getAccountId() {

		return accountId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_recharge_history.account_id
	 * 
	 * @param accountId
	 *            the value for nuist_recharge_history.account_id
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public void setAccountId( Integer accountId ) {

		this.accountId = accountId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_recharge_history.recharge_amount
	 * 
	 * @return the value of nuist_recharge_history.recharge_amount
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public Double getRechargeAmount() {

		return rechargeAmount;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_recharge_history.recharge_amount
	 * 
	 * @param rechargeAmount
	 *            the value for nuist_recharge_history.recharge_amount
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public void setRechargeAmount( Double rechargeAmount ) {

		this.rechargeAmount = rechargeAmount;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_recharge_history.add_time
	 * 
	 * @return the value of nuist_recharge_history.add_time
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public Date getAddTime() {

		return addTime;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_recharge_history.add_time
	 * 
	 * @param addTime
	 *            the value for nuist_recharge_history.add_time
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public void setAddTime( Date addTime ) {

		this.addTime = addTime;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_recharge_history.add_ip
	 * 
	 * @return the value of nuist_recharge_history.add_ip
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public String getAddIp() {

		return addIp;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_recharge_history.add_ip
	 * 
	 * @param addIp
	 *            the value for nuist_recharge_history.add_ip
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public void setAddIp( String addIp ) {

		this.addIp = addIp;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_recharge_history.country
	 * 
	 * @return the value of nuist_recharge_history.country
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public String getCountry() {

		return country;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_recharge_history.country
	 * 
	 * @param country
	 *            the value for nuist_recharge_history.country
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public void setCountry( String country ) {

		this.country = country;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_recharge_history.country_id
	 * 
	 * @return the value of nuist_recharge_history.country_id
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public String getCountryId() {

		return countryId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_recharge_history.country_id
	 * 
	 * @param countryId
	 *            the value for nuist_recharge_history.country_id
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public void setCountryId( String countryId ) {

		this.countryId = countryId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_recharge_history.area
	 * 
	 * @return the value of nuist_recharge_history.area
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public String getArea() {

		return area;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_recharge_history.area
	 * 
	 * @param area
	 *            the value for nuist_recharge_history.area
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public void setArea( String area ) {

		this.area = area;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_recharge_history.area_id
	 * 
	 * @return the value of nuist_recharge_history.area_id
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public String getAreaId() {

		return areaId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_recharge_history.area_id
	 * 
	 * @param areaId
	 *            the value for nuist_recharge_history.area_id
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public void setAreaId( String areaId ) {

		this.areaId = areaId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_recharge_history.region
	 * 
	 * @return the value of nuist_recharge_history.region
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public String getRegion() {

		return region;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_recharge_history.region
	 * 
	 * @param region
	 *            the value for nuist_recharge_history.region
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public void setRegion( String region ) {

		this.region = region;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_recharge_history.region_id
	 * 
	 * @return the value of nuist_recharge_history.region_id
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public String getRegionId() {

		return regionId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_recharge_history.region_id
	 * 
	 * @param regionId
	 *            the value for nuist_recharge_history.region_id
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public void setRegionId( String regionId ) {

		this.regionId = regionId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_recharge_history.city
	 * 
	 * @return the value of nuist_recharge_history.city
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public String getCity() {

		return city;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_recharge_history.city
	 * 
	 * @param city
	 *            the value for nuist_recharge_history.city
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public void setCity( String city ) {

		this.city = city;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_recharge_history.city_id
	 * 
	 * @return the value of nuist_recharge_history.city_id
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public String getCityId() {

		return cityId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_recharge_history.city_id
	 * 
	 * @param cityId
	 *            the value for nuist_recharge_history.city_id
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public void setCityId( String cityId ) {

		this.cityId = cityId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_recharge_history.isp
	 * 
	 * @return the value of nuist_recharge_history.isp
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public String getIsp() {

		return isp;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_recharge_history.isp
	 * 
	 * @param isp
	 *            the value for nuist_recharge_history.isp
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public void setIsp( String isp ) {

		this.isp = isp;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_recharge_history.isp_id
	 * 
	 * @return the value of nuist_recharge_history.isp_id
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public String getIspId() {

		return ispId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_recharge_history.isp_id
	 * 
	 * @param ispId
	 *            the value for nuist_recharge_history.isp_id
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public void setIspId( String ispId ) {

		this.ispId = ispId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_recharge_history.explorer_version
	 * 
	 * @return the value of nuist_recharge_history.explorer_version
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public String getExplorerVersion() {

		return explorerVersion;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_recharge_history.explorer_version
	 * 
	 * @param explorerVersion
	 *            the value for nuist_recharge_history.explorer_version
	 * @ibatorgenerated Mon Feb 23 22:18:02 CST 2015
	 */
	public void setExplorerVersion( String explorerVersion ) {

		this.explorerVersion = explorerVersion;
	}
}