package com.linklife.domain.ibator;

import java.util.Date;

import com.linklife.domain.base.BaseDomain;
import com.linklife.repository.base.SqlMap;

/**
 * <p>
 * NuistSuggest.java
 * </p>
 * 
 * <pre>
 * 南信大一卡�?�用户反馈实�?
 * </pre>
 * 
 * @author caisupeng
 */
@SqlMap( Name = "nuist_suggest", Class = NuistSuggest.class )
public class NuistSuggest<T, U> extends BaseDomain<T, U> {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_suggest.suggest_id
	 * 
	 * @ibatorgenerated Mon Feb 09 19:40:42 CST 2015
	 */
	private Integer suggestId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_suggest.usernumber
	 * 
	 * @ibatorgenerated Mon Feb 09 19:40:42 CST 2015
	 */
	private String usernumber;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_suggest.suggest
	 * 
	 * @ibatorgenerated Mon Feb 09 19:40:42 CST 2015
	 */
	private String suggest;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_suggest.addtime
	 * 
	 * @ibatorgenerated Mon Feb 09 19:40:42 CST 2015
	 */
	private Date addtime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_suggest.answer
	 * 
	 * @ibatorgenerated Mon Feb 09 19:40:42 CST 2015
	 */
	private String answer;


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_suggest.suggest_id
	 * 
	 * @return the value of nuist_suggest.suggest_id
	 * @ibatorgenerated Mon Feb 09 19:40:42 CST 2015
	 */
	public Integer getSuggestId() {

		return suggestId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_suggest.suggest_id
	 * 
	 * @param suggestId
	 *            the value for nuist_suggest.suggest_id
	 * @ibatorgenerated Mon Feb 09 19:40:42 CST 2015
	 */
	public void setSuggestId( Integer suggestId ) {

		this.suggestId = suggestId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_suggest.usernumber
	 * 
	 * @return the value of nuist_suggest.usernumber
	 * @ibatorgenerated Mon Feb 09 19:40:42 CST 2015
	 */
	public String getUsernumber() {

		return usernumber;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_suggest.usernumber
	 * 
	 * @param usernumber
	 *            the value for nuist_suggest.usernumber
	 * @ibatorgenerated Mon Feb 09 19:40:42 CST 2015
	 */
	public void setUsernumber( String usernumber ) {

		this.usernumber = usernumber;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_suggest.suggest
	 * 
	 * @return the value of nuist_suggest.suggest
	 * @ibatorgenerated Mon Feb 09 19:40:42 CST 2015
	 */
	public String getSuggest() {

		return suggest;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_suggest.suggest
	 * 
	 * @param suggest
	 *            the value for nuist_suggest.suggest
	 * @ibatorgenerated Mon Feb 09 19:40:42 CST 2015
	 */
	public void setSuggest( String suggest ) {

		this.suggest = suggest;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_suggest.addtime
	 * 
	 * @return the value of nuist_suggest.addtime
	 * @ibatorgenerated Mon Feb 09 19:40:42 CST 2015
	 */
	public Date getAddtime() {

		return addtime;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_suggest.addtime
	 * 
	 * @param addtime
	 *            the value for nuist_suggest.addtime
	 * @ibatorgenerated Mon Feb 09 19:40:42 CST 2015
	 */
	public void setAddtime( Date addtime ) {

		this.addtime = addtime;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_suggest.answer
	 * 
	 * @return the value of nuist_suggest.answer
	 * @ibatorgenerated Mon Feb 09 19:40:42 CST 2015
	 */
	public String getAnswer() {

		return answer;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_suggest.answer
	 * 
	 * @param answer
	 *            the value for nuist_suggest.answer
	 * @ibatorgenerated Mon Feb 09 19:40:42 CST 2015
	 */
	public void setAnswer( String answer ) {

		this.answer = answer;
	}
}