package com.linklife.domain.ibator;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class NuistInfoExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table nuist_info
	 * @ibatorgenerated  Tue Jul 14 21:09:31 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table nuist_info
	 * @ibatorgenerated  Tue Jul 14 21:09:31 CST 2015
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_info
	 * @ibatorgenerated  Tue Jul 14 21:09:31 CST 2015
	 */
	public NuistInfoExample() {

		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_info
	 * @ibatorgenerated  Tue Jul 14 21:09:31 CST 2015
	 */
	protected NuistInfoExample( NuistInfoExample example ) {

		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_info
	 * @ibatorgenerated  Tue Jul 14 21:09:31 CST 2015
	 */
	public void setOrderByClause( String orderByClause ) {

		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_info
	 * @ibatorgenerated  Tue Jul 14 21:09:31 CST 2015
	 */
	public String getOrderByClause() {

		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_info
	 * @ibatorgenerated  Tue Jul 14 21:09:31 CST 2015
	 */
	public List getOredCriteria() {

		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_info
	 * @ibatorgenerated  Tue Jul 14 21:09:31 CST 2015
	 */
	public void or( Criteria criteria ) {

		oredCriteria.add( criteria );
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_info
	 * @ibatorgenerated  Tue Jul 14 21:09:31 CST 2015
	 */
	public Criteria createCriteria() {

		Criteria criteria = createCriteriaInternal();
		if( oredCriteria.size() == 0 ) {
			oredCriteria.add( criteria );
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_info
	 * @ibatorgenerated  Tue Jul 14 21:09:31 CST 2015
	 */
	protected Criteria createCriteriaInternal() {

		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table nuist_info
	 * @ibatorgenerated  Tue Jul 14 21:09:31 CST 2015
	 */
	public void clear() {

		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table nuist_info
	 * @ibatorgenerated  Tue Jul 14 21:09:31 CST 2015
	 */
	public static class Criteria {

		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;


		protected Criteria() {

			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}


		public boolean isValid() {

			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}


		public List getCriteriaWithoutValue() {

			return criteriaWithoutValue;
		}


		public List getCriteriaWithSingleValue() {

			return criteriaWithSingleValue;
		}


		public List getCriteriaWithListValue() {

			return criteriaWithListValue;
		}


		public List getCriteriaWithBetweenValue() {

			return criteriaWithBetweenValue;
		}


		protected void addCriterion( String condition ) {

			if( condition == null ) {
				throw new RuntimeException( "Value for condition cannot be null" );
			}
			criteriaWithoutValue.add( condition );
		}


		protected void addCriterion( String condition, Object value, String property ) {

			if( value == null ) {
				throw new RuntimeException( "Value for " + property + " cannot be null" );
			}
			Map map = new HashMap();
			map.put( "condition", condition );
			map.put( "value", value );
			criteriaWithSingleValue.add( map );
		}


		protected void addCriterion( String condition, List values, String property ) {

			if( values == null || values.size() == 0 ) {
				throw new RuntimeException( "Value list for " + property + " cannot be null or empty" );
			}
			Map map = new HashMap();
			map.put( "condition", condition );
			map.put( "values", values );
			criteriaWithListValue.add( map );
		}


		protected void addCriterion( String condition, Object value1, Object value2, String property ) {

			if( value1 == null || value2 == null ) {
				throw new RuntimeException( "Between values for " + property + " cannot be null" );
			}
			List list = new ArrayList();
			list.add( value1 );
			list.add( value2 );
			Map map = new HashMap();
			map.put( "condition", condition );
			map.put( "values", list );
			criteriaWithBetweenValue.add( map );
		}


		public Criteria andAccountIdIsNull() {

			addCriterion( "account_id is null" );
			return this;
		}


		public Criteria andAccountIdIsNotNull() {

			addCriterion( "account_id is not null" );
			return this;
		}


		public Criteria andAccountIdEqualTo( Integer value ) {

			addCriterion( "account_id =", value, "accountId" );
			return this;
		}


		public Criteria andAccountIdNotEqualTo( Integer value ) {

			addCriterion( "account_id <>", value, "accountId" );
			return this;
		}


		public Criteria andAccountIdGreaterThan( Integer value ) {

			addCriterion( "account_id >", value, "accountId" );
			return this;
		}


		public Criteria andAccountIdGreaterThanOrEqualTo( Integer value ) {

			addCriterion( "account_id >=", value, "accountId" );
			return this;
		}


		public Criteria andAccountIdLessThan( Integer value ) {

			addCriterion( "account_id <", value, "accountId" );
			return this;
		}


		public Criteria andAccountIdLessThanOrEqualTo( Integer value ) {

			addCriterion( "account_id <=", value, "accountId" );
			return this;
		}


		public Criteria andAccountIdIn( List values ) {

			addCriterion( "account_id in", values, "accountId" );
			return this;
		}


		public Criteria andAccountIdNotIn( List values ) {

			addCriterion( "account_id not in", values, "accountId" );
			return this;
		}


		public Criteria andAccountIdBetween( Integer value1, Integer value2 ) {

			addCriterion( "account_id between", value1, value2, "accountId" );
			return this;
		}


		public Criteria andAccountIdNotBetween( Integer value1, Integer value2 ) {

			addCriterion( "account_id not between", value1, value2, "accountId" );
			return this;
		}


		public Criteria andUsernameIsNull() {

			addCriterion( "username is null" );
			return this;
		}


		public Criteria andUsernameIsNotNull() {

			addCriterion( "username is not null" );
			return this;
		}


		public Criteria andUsernameEqualTo( String value ) {

			addCriterion( "username =", value, "username" );
			return this;
		}


		public Criteria andUsernameNotEqualTo( String value ) {

			addCriterion( "username <>", value, "username" );
			return this;
		}


		public Criteria andUsernameGreaterThan( String value ) {

			addCriterion( "username >", value, "username" );
			return this;
		}


		public Criteria andUsernameGreaterThanOrEqualTo( String value ) {

			addCriterion( "username >=", value, "username" );
			return this;
		}


		public Criteria andUsernameLessThan( String value ) {

			addCriterion( "username <", value, "username" );
			return this;
		}


		public Criteria andUsernameLessThanOrEqualTo( String value ) {

			addCriterion( "username <=", value, "username" );
			return this;
		}


		public Criteria andUsernameLike( String value ) {

			addCriterion( "username like", value, "username" );
			return this;
		}


		public Criteria andUsernameNotLike( String value ) {

			addCriterion( "username not like", value, "username" );
			return this;
		}


		public Criteria andUsernameIn( List values ) {

			addCriterion( "username in", values, "username" );
			return this;
		}


		public Criteria andUsernameNotIn( List values ) {

			addCriterion( "username not in", values, "username" );
			return this;
		}


		public Criteria andUsernameBetween( String value1, String value2 ) {

			addCriterion( "username between", value1, value2, "username" );
			return this;
		}


		public Criteria andUsernameNotBetween( String value1, String value2 ) {

			addCriterion( "username not between", value1, value2, "username" );
			return this;
		}


		public Criteria andUsernumberIsNull() {

			addCriterion( "usernumber is null" );
			return this;
		}


		public Criteria andUsernumberIsNotNull() {

			addCriterion( "usernumber is not null" );
			return this;
		}


		public Criteria andUsernumberEqualTo( String value ) {

			addCriterion( "usernumber =", value, "usernumber" );
			return this;
		}


		public Criteria andUsernumberNotEqualTo( String value ) {

			addCriterion( "usernumber <>", value, "usernumber" );
			return this;
		}


		public Criteria andUsernumberGreaterThan( String value ) {

			addCriterion( "usernumber >", value, "usernumber" );
			return this;
		}


		public Criteria andUsernumberGreaterThanOrEqualTo( String value ) {

			addCriterion( "usernumber >=", value, "usernumber" );
			return this;
		}


		public Criteria andUsernumberLessThan( String value ) {

			addCriterion( "usernumber <", value, "usernumber" );
			return this;
		}


		public Criteria andUsernumberLessThanOrEqualTo( String value ) {

			addCriterion( "usernumber <=", value, "usernumber" );
			return this;
		}


		public Criteria andUsernumberLike( String value ) {

			addCriterion( "usernumber like", value, "usernumber" );
			return this;
		}


		public Criteria andUsernumberNotLike( String value ) {

			addCriterion( "usernumber not like", value, "usernumber" );
			return this;
		}


		public Criteria andUsernumberIn( List values ) {

			addCriterion( "usernumber in", values, "usernumber" );
			return this;
		}


		public Criteria andUsernumberNotIn( List values ) {

			addCriterion( "usernumber not in", values, "usernumber" );
			return this;
		}


		public Criteria andUsernumberBetween( String value1, String value2 ) {

			addCriterion( "usernumber between", value1, value2, "usernumber" );
			return this;
		}


		public Criteria andUsernumberNotBetween( String value1, String value2 ) {

			addCriterion( "usernumber not between", value1, value2, "usernumber" );
			return this;
		}


		public Criteria andCardidIsNull() {

			addCriterion( "cardid is null" );
			return this;
		}


		public Criteria andCardidIsNotNull() {

			addCriterion( "cardid is not null" );
			return this;
		}


		public Criteria andCardidEqualTo( String value ) {

			addCriterion( "cardid =", value, "cardid" );
			return this;
		}


		public Criteria andCardidNotEqualTo( String value ) {

			addCriterion( "cardid <>", value, "cardid" );
			return this;
		}


		public Criteria andCardidGreaterThan( String value ) {

			addCriterion( "cardid >", value, "cardid" );
			return this;
		}


		public Criteria andCardidGreaterThanOrEqualTo( String value ) {

			addCriterion( "cardid >=", value, "cardid" );
			return this;
		}


		public Criteria andCardidLessThan( String value ) {

			addCriterion( "cardid <", value, "cardid" );
			return this;
		}


		public Criteria andCardidLessThanOrEqualTo( String value ) {

			addCriterion( "cardid <=", value, "cardid" );
			return this;
		}


		public Criteria andCardidLike( String value ) {

			addCriterion( "cardid like", value, "cardid" );
			return this;
		}


		public Criteria andCardidNotLike( String value ) {

			addCriterion( "cardid not like", value, "cardid" );
			return this;
		}


		public Criteria andCardidIn( List values ) {

			addCriterion( "cardid in", values, "cardid" );
			return this;
		}


		public Criteria andCardidNotIn( List values ) {

			addCriterion( "cardid not in", values, "cardid" );
			return this;
		}


		public Criteria andCardidBetween( String value1, String value2 ) {

			addCriterion( "cardid between", value1, value2, "cardid" );
			return this;
		}


		public Criteria andCardidNotBetween( String value1, String value2 ) {

			addCriterion( "cardid not between", value1, value2, "cardid" );
			return this;
		}


		public Criteria andBalanceIsNull() {

			addCriterion( "balance is null" );
			return this;
		}


		public Criteria andBalanceIsNotNull() {

			addCriterion( "balance is not null" );
			return this;
		}


		public Criteria andBalanceEqualTo( BigDecimal value ) {

			addCriterion( "balance =", value, "balance" );
			return this;
		}


		public Criteria andBalanceNotEqualTo( BigDecimal value ) {

			addCriterion( "balance <>", value, "balance" );
			return this;
		}


		public Criteria andBalanceGreaterThan( BigDecimal value ) {

			addCriterion( "balance >", value, "balance" );
			return this;
		}


		public Criteria andBalanceGreaterThanOrEqualTo( BigDecimal value ) {

			addCriterion( "balance >=", value, "balance" );
			return this;
		}


		public Criteria andBalanceLessThan( BigDecimal value ) {

			addCriterion( "balance <", value, "balance" );
			return this;
		}


		public Criteria andBalanceLessThanOrEqualTo( BigDecimal value ) {

			addCriterion( "balance <=", value, "balance" );
			return this;
		}


		public Criteria andBalanceIn( List values ) {

			addCriterion( "balance in", values, "balance" );
			return this;
		}


		public Criteria andBalanceNotIn( List values ) {

			addCriterion( "balance not in", values, "balance" );
			return this;
		}


		public Criteria andBalanceBetween( BigDecimal value1, BigDecimal value2 ) {

			addCriterion( "balance between", value1, value2, "balance" );
			return this;
		}


		public Criteria andBalanceNotBetween( BigDecimal value1, BigDecimal value2 ) {

			addCriterion( "balance not between", value1, value2, "balance" );
			return this;
		}


		public Criteria andBandcardIsNull() {

			addCriterion( "bandcard is null" );
			return this;
		}


		public Criteria andBandcardIsNotNull() {

			addCriterion( "bandcard is not null" );
			return this;
		}


		public Criteria andBandcardEqualTo( String value ) {

			addCriterion( "bandcard =", value, "bandcard" );
			return this;
		}


		public Criteria andBandcardNotEqualTo( String value ) {

			addCriterion( "bandcard <>", value, "bandcard" );
			return this;
		}


		public Criteria andBandcardGreaterThan( String value ) {

			addCriterion( "bandcard >", value, "bandcard" );
			return this;
		}


		public Criteria andBandcardGreaterThanOrEqualTo( String value ) {

			addCriterion( "bandcard >=", value, "bandcard" );
			return this;
		}


		public Criteria andBandcardLessThan( String value ) {

			addCriterion( "bandcard <", value, "bandcard" );
			return this;
		}


		public Criteria andBandcardLessThanOrEqualTo( String value ) {

			addCriterion( "bandcard <=", value, "bandcard" );
			return this;
		}


		public Criteria andBandcardLike( String value ) {

			addCriterion( "bandcard like", value, "bandcard" );
			return this;
		}


		public Criteria andBandcardNotLike( String value ) {

			addCriterion( "bandcard not like", value, "bandcard" );
			return this;
		}


		public Criteria andBandcardIn( List values ) {

			addCriterion( "bandcard in", values, "bandcard" );
			return this;
		}


		public Criteria andBandcardNotIn( List values ) {

			addCriterion( "bandcard not in", values, "bandcard" );
			return this;
		}


		public Criteria andBandcardBetween( String value1, String value2 ) {

			addCriterion( "bandcard between", value1, value2, "bandcard" );
			return this;
		}


		public Criteria andBandcardNotBetween( String value1, String value2 ) {

			addCriterion( "bandcard not between", value1, value2, "bandcard" );
			return this;
		}


		public Criteria andStatusIsNull() {

			addCriterion( "status is null" );
			return this;
		}


		public Criteria andStatusIsNotNull() {

			addCriterion( "status is not null" );
			return this;
		}


		public Criteria andStatusEqualTo( String value ) {

			addCriterion( "status =", value, "status" );
			return this;
		}


		public Criteria andStatusNotEqualTo( String value ) {

			addCriterion( "status <>", value, "status" );
			return this;
		}


		public Criteria andStatusGreaterThan( String value ) {

			addCriterion( "status >", value, "status" );
			return this;
		}


		public Criteria andStatusGreaterThanOrEqualTo( String value ) {

			addCriterion( "status >=", value, "status" );
			return this;
		}


		public Criteria andStatusLessThan( String value ) {

			addCriterion( "status <", value, "status" );
			return this;
		}


		public Criteria andStatusLessThanOrEqualTo( String value ) {

			addCriterion( "status <=", value, "status" );
			return this;
		}


		public Criteria andStatusLike( String value ) {

			addCriterion( "status like", value, "status" );
			return this;
		}


		public Criteria andStatusNotLike( String value ) {

			addCriterion( "status not like", value, "status" );
			return this;
		}


		public Criteria andStatusIn( List values ) {

			addCriterion( "status in", values, "status" );
			return this;
		}


		public Criteria andStatusNotIn( List values ) {

			addCriterion( "status not in", values, "status" );
			return this;
		}


		public Criteria andStatusBetween( String value1, String value2 ) {

			addCriterion( "status between", value1, value2, "status" );
			return this;
		}


		public Criteria andStatusNotBetween( String value1, String value2 ) {

			addCriterion( "status not between", value1, value2, "status" );
			return this;
		}


		public Criteria andEducationIsNull() {

			addCriterion( "education is null" );
			return this;
		}


		public Criteria andEducationIsNotNull() {

			addCriterion( "education is not null" );
			return this;
		}


		public Criteria andEducationEqualTo( String value ) {

			addCriterion( "education =", value, "education" );
			return this;
		}


		public Criteria andEducationNotEqualTo( String value ) {

			addCriterion( "education <>", value, "education" );
			return this;
		}


		public Criteria andEducationGreaterThan( String value ) {

			addCriterion( "education >", value, "education" );
			return this;
		}


		public Criteria andEducationGreaterThanOrEqualTo( String value ) {

			addCriterion( "education >=", value, "education" );
			return this;
		}


		public Criteria andEducationLessThan( String value ) {

			addCriterion( "education <", value, "education" );
			return this;
		}


		public Criteria andEducationLessThanOrEqualTo( String value ) {

			addCriterion( "education <=", value, "education" );
			return this;
		}


		public Criteria andEducationLike( String value ) {

			addCriterion( "education like", value, "education" );
			return this;
		}


		public Criteria andEducationNotLike( String value ) {

			addCriterion( "education not like", value, "education" );
			return this;
		}


		public Criteria andEducationIn( List values ) {

			addCriterion( "education in", values, "education" );
			return this;
		}


		public Criteria andEducationNotIn( List values ) {

			addCriterion( "education not in", values, "education" );
			return this;
		}


		public Criteria andEducationBetween( String value1, String value2 ) {

			addCriterion( "education between", value1, value2, "education" );
			return this;
		}


		public Criteria andEducationNotBetween( String value1, String value2 ) {

			addCriterion( "education not between", value1, value2, "education" );
			return this;
		}


		public Criteria andClassIdIsNull() {

			addCriterion( "class_id is null" );
			return this;
		}


		public Criteria andClassIdIsNotNull() {

			addCriterion( "class_id is not null" );
			return this;
		}


		public Criteria andClassIdEqualTo( Integer value ) {

			addCriterion( "class_id =", value, "classId" );
			return this;
		}


		public Criteria andClassIdNotEqualTo( Integer value ) {

			addCriterion( "class_id <>", value, "classId" );
			return this;
		}


		public Criteria andClassIdGreaterThan( Integer value ) {

			addCriterion( "class_id >", value, "classId" );
			return this;
		}


		public Criteria andClassIdGreaterThanOrEqualTo( Integer value ) {

			addCriterion( "class_id >=", value, "classId" );
			return this;
		}


		public Criteria andClassIdLessThan( Integer value ) {

			addCriterion( "class_id <", value, "classId" );
			return this;
		}


		public Criteria andClassIdLessThanOrEqualTo( Integer value ) {

			addCriterion( "class_id <=", value, "classId" );
			return this;
		}


		public Criteria andClassIdIn( List values ) {

			addCriterion( "class_id in", values, "classId" );
			return this;
		}


		public Criteria andClassIdNotIn( List values ) {

			addCriterion( "class_id not in", values, "classId" );
			return this;
		}


		public Criteria andClassIdBetween( Integer value1, Integer value2 ) {

			addCriterion( "class_id between", value1, value2, "classId" );
			return this;
		}


		public Criteria andClassIdNotBetween( Integer value1, Integer value2 ) {

			addCriterion( "class_id not between", value1, value2, "classId" );
			return this;
		}


		public Criteria andPeriodIsNull() {

			addCriterion( "period is null" );
			return this;
		}


		public Criteria andPeriodIsNotNull() {

			addCriterion( "period is not null" );
			return this;
		}


		public Criteria andPeriodEqualTo( String value ) {

			addCriterion( "period =", value, "period" );
			return this;
		}


		public Criteria andPeriodNotEqualTo( String value ) {

			addCriterion( "period <>", value, "period" );
			return this;
		}


		public Criteria andPeriodGreaterThan( String value ) {

			addCriterion( "period >", value, "period" );
			return this;
		}


		public Criteria andPeriodGreaterThanOrEqualTo( String value ) {

			addCriterion( "period >=", value, "period" );
			return this;
		}


		public Criteria andPeriodLessThan( String value ) {

			addCriterion( "period <", value, "period" );
			return this;
		}


		public Criteria andPeriodLessThanOrEqualTo( String value ) {

			addCriterion( "period <=", value, "period" );
			return this;
		}


		public Criteria andPeriodLike( String value ) {

			addCriterion( "period like", value, "period" );
			return this;
		}


		public Criteria andPeriodNotLike( String value ) {

			addCriterion( "period not like", value, "period" );
			return this;
		}


		public Criteria andPeriodIn( List values ) {

			addCriterion( "period in", values, "period" );
			return this;
		}


		public Criteria andPeriodNotIn( List values ) {

			addCriterion( "period not in", values, "period" );
			return this;
		}


		public Criteria andPeriodBetween( String value1, String value2 ) {

			addCriterion( "period between", value1, value2, "period" );
			return this;
		}


		public Criteria andPeriodNotBetween( String value1, String value2 ) {

			addCriterion( "period not between", value1, value2, "period" );
			return this;
		}


		public Criteria andCodeIsNull() {

			addCriterion( "code is null" );
			return this;
		}


		public Criteria andCodeIsNotNull() {

			addCriterion( "code is not null" );
			return this;
		}


		public Criteria andCodeEqualTo( String value ) {

			addCriterion( "code =", value, "code" );
			return this;
		}


		public Criteria andCodeNotEqualTo( String value ) {

			addCriterion( "code <>", value, "code" );
			return this;
		}


		public Criteria andCodeGreaterThan( String value ) {

			addCriterion( "code >", value, "code" );
			return this;
		}


		public Criteria andCodeGreaterThanOrEqualTo( String value ) {

			addCriterion( "code >=", value, "code" );
			return this;
		}


		public Criteria andCodeLessThan( String value ) {

			addCriterion( "code <", value, "code" );
			return this;
		}


		public Criteria andCodeLessThanOrEqualTo( String value ) {

			addCriterion( "code <=", value, "code" );
			return this;
		}


		public Criteria andCodeLike( String value ) {

			addCriterion( "code like", value, "code" );
			return this;
		}


		public Criteria andCodeNotLike( String value ) {

			addCriterion( "code not like", value, "code" );
			return this;
		}


		public Criteria andCodeIn( List values ) {

			addCriterion( "code in", values, "code" );
			return this;
		}


		public Criteria andCodeNotIn( List values ) {

			addCriterion( "code not in", values, "code" );
			return this;
		}


		public Criteria andCodeBetween( String value1, String value2 ) {

			addCriterion( "code between", value1, value2, "code" );
			return this;
		}


		public Criteria andCodeNotBetween( String value1, String value2 ) {

			addCriterion( "code not between", value1, value2, "code" );
			return this;
		}


		public Criteria andAddLocationIsNull() {

			addCriterion( "add_location is null" );
			return this;
		}


		public Criteria andAddLocationIsNotNull() {

			addCriterion( "add_location is not null" );
			return this;
		}


		public Criteria andAddLocationEqualTo( String value ) {

			addCriterion( "add_location =", value, "addLocation" );
			return this;
		}


		public Criteria andAddLocationNotEqualTo( String value ) {

			addCriterion( "add_location <>", value, "addLocation" );
			return this;
		}


		public Criteria andAddLocationGreaterThan( String value ) {

			addCriterion( "add_location >", value, "addLocation" );
			return this;
		}


		public Criteria andAddLocationGreaterThanOrEqualTo( String value ) {

			addCriterion( "add_location >=", value, "addLocation" );
			return this;
		}


		public Criteria andAddLocationLessThan( String value ) {

			addCriterion( "add_location <", value, "addLocation" );
			return this;
		}


		public Criteria andAddLocationLessThanOrEqualTo( String value ) {

			addCriterion( "add_location <=", value, "addLocation" );
			return this;
		}


		public Criteria andAddLocationLike( String value ) {

			addCriterion( "add_location like", value, "addLocation" );
			return this;
		}


		public Criteria andAddLocationNotLike( String value ) {

			addCriterion( "add_location not like", value, "addLocation" );
			return this;
		}


		public Criteria andAddLocationIn( List values ) {

			addCriterion( "add_location in", values, "addLocation" );
			return this;
		}


		public Criteria andAddLocationNotIn( List values ) {

			addCriterion( "add_location not in", values, "addLocation" );
			return this;
		}


		public Criteria andAddLocationBetween( String value1, String value2 ) {

			addCriterion( "add_location between", value1, value2, "addLocation" );
			return this;
		}


		public Criteria andAddLocationNotBetween( String value1, String value2 ) {

			addCriterion( "add_location not between", value1, value2, "addLocation" );
			return this;
		}


		public Criteria andAddTimeIsNull() {

			addCriterion( "add_time is null" );
			return this;
		}


		public Criteria andAddTimeIsNotNull() {

			addCriterion( "add_time is not null" );
			return this;
		}


		public Criteria andAddTimeEqualTo( Date value ) {

			addCriterion( "add_time =", value, "addTime" );
			return this;
		}


		public Criteria andAddTimeNotEqualTo( Date value ) {

			addCriterion( "add_time <>", value, "addTime" );
			return this;
		}


		public Criteria andAddTimeGreaterThan( Date value ) {

			addCriterion( "add_time >", value, "addTime" );
			return this;
		}


		public Criteria andAddTimeGreaterThanOrEqualTo( Date value ) {

			addCriterion( "add_time >=", value, "addTime" );
			return this;
		}


		public Criteria andAddTimeLessThan( Date value ) {

			addCriterion( "add_time <", value, "addTime" );
			return this;
		}


		public Criteria andAddTimeLessThanOrEqualTo( Date value ) {

			addCriterion( "add_time <=", value, "addTime" );
			return this;
		}


		public Criteria andAddTimeIn( List values ) {

			addCriterion( "add_time in", values, "addTime" );
			return this;
		}


		public Criteria andAddTimeNotIn( List values ) {

			addCriterion( "add_time not in", values, "addTime" );
			return this;
		}


		public Criteria andAddTimeBetween( Date value1, Date value2 ) {

			addCriterion( "add_time between", value1, value2, "addTime" );
			return this;
		}


		public Criteria andAddTimeNotBetween( Date value1, Date value2 ) {

			addCriterion( "add_time not between", value1, value2, "addTime" );
			return this;
		}


		public Criteria andAddCityIsNull() {

			addCriterion( "add_city is null" );
			return this;
		}


		public Criteria andAddCityIsNotNull() {

			addCriterion( "add_city is not null" );
			return this;
		}


		public Criteria andAddCityEqualTo( String value ) {

			addCriterion( "add_city =", value, "addCity" );
			return this;
		}


		public Criteria andAddCityNotEqualTo( String value ) {

			addCriterion( "add_city <>", value, "addCity" );
			return this;
		}


		public Criteria andAddCityGreaterThan( String value ) {

			addCriterion( "add_city >", value, "addCity" );
			return this;
		}


		public Criteria andAddCityGreaterThanOrEqualTo( String value ) {

			addCriterion( "add_city >=", value, "addCity" );
			return this;
		}


		public Criteria andAddCityLessThan( String value ) {

			addCriterion( "add_city <", value, "addCity" );
			return this;
		}


		public Criteria andAddCityLessThanOrEqualTo( String value ) {

			addCriterion( "add_city <=", value, "addCity" );
			return this;
		}


		public Criteria andAddCityLike( String value ) {

			addCriterion( "add_city like", value, "addCity" );
			return this;
		}


		public Criteria andAddCityNotLike( String value ) {

			addCriterion( "add_city not like", value, "addCity" );
			return this;
		}


		public Criteria andAddCityIn( List values ) {

			addCriterion( "add_city in", values, "addCity" );
			return this;
		}


		public Criteria andAddCityNotIn( List values ) {

			addCriterion( "add_city not in", values, "addCity" );
			return this;
		}


		public Criteria andAddCityBetween( String value1, String value2 ) {

			addCriterion( "add_city between", value1, value2, "addCity" );
			return this;
		}


		public Criteria andAddCityNotBetween( String value1, String value2 ) {

			addCriterion( "add_city not between", value1, value2, "addCity" );
			return this;
		}
	}
}