package com.linklife.domain.ibator;

import com.linklife.domain.base.BaseDomain;
import com.linklife.repository.base.SqlMap;

@SqlMap( Name = "nuist_course", Class = NuistCourse.class )
public class NuistCourse<T, U> extends BaseDomain<T, U> {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_course.course_id
	 *
	 * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
	 */
	private Integer courseId;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_course.course_name
	 *
	 * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
	 */
	private String courseName;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_course.course_subject
	 *
	 * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
	 */
	private Integer courseSubject;


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_course.course_id
	 *
	 * @return the value of nuist_course.course_id
	 *
	 * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
	 */
	public Integer getCourseId() {

		return courseId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_course.course_id
	 *
	 * @param courseId
	 *            the value for nuist_course.course_id
	 *
	 * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
	 */
	public void setCourseId( Integer courseId ) {

		this.courseId = courseId;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_course.course_name
	 *
	 * @return the value of nuist_course.course_name
	 *
	 * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
	 */
	public String getCourseName() {

		return courseName;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_course.course_name
	 *
	 * @param courseName
	 *            the value for nuist_course.course_name
	 *
	 * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
	 */
	public void setCourseName( String courseName ) {

		this.courseName = courseName;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_course.course_subject
	 *
	 * @return the value of nuist_course.course_subject
	 *
	 * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
	 */
	public Integer getCourseSubject() {

		return courseSubject;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_course.course_subject
	 *
	 * @param courseSubject
	 *            the value for nuist_course.course_subject
	 *
	 * @ibatorgenerated Sun Jul 12 13:22:43 CST 2015
	 */
	public void setCourseSubject( Integer courseSubject ) {

		this.courseSubject = courseSubject;
	}
}