package com.linklife.domain.ibator;

import java.util.Date;

import com.linklife.domain.base.BaseDomain;
import com.linklife.repository.base.SqlMap;

/**
 * <p>
 * NuistScoreHistory.java
 * </p>
 * 
 * <pre>
 * 用户成绩表对应实体类
 * </pre>
 * 
 * @author caisupeng
 */
@SqlMap(Name = "nuist_score_history", Class = NuistScoreHistory.class)
public class NuistScoreHistory<T, U> extends BaseDomain<T, U> {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column nuist_score_history.score_id
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	private Long scoreId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column nuist_score_history.account_id
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	private Long accountId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column nuist_score_history.course
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	private String course;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column nuist_score_history.year
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	private String year;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column nuist_score_history.term
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	private Integer term;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column nuist_score_history.score
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	private Double score;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column nuist_score_history.time
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	private Date time;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column nuist_score_history.credit
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	private Double credit;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column nuist_score_history.grade
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	private String grade;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column nuist_score_history.score_id
	 * @return  the value of nuist_score_history.score_id
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	public Long getScoreId() {

		return scoreId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column nuist_score_history.score_id
	 * @param scoreId  the value for nuist_score_history.score_id
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	public void setScoreId( Long scoreId ) {

		this.scoreId = scoreId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column nuist_score_history.account_id
	 * @return  the value of nuist_score_history.account_id
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	public Long getAccountId() {

		return accountId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column nuist_score_history.account_id
	 * @param accountId  the value for nuist_score_history.account_id
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	public void setAccountId( Long accountId ) {

		this.accountId = accountId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column nuist_score_history.course
	 * @return  the value of nuist_score_history.course
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	public String getCourse() {

		return course;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column nuist_score_history.course
	 * @param course  the value for nuist_score_history.course
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	public void setCourse( String course ) {

		this.course = course;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column nuist_score_history.year
	 * @return  the value of nuist_score_history.year
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	public String getYear() {

		return year;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column nuist_score_history.year
	 * @param year  the value for nuist_score_history.year
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	public void setYear( String year ) {

		this.year = year;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column nuist_score_history.term
	 * @return  the value of nuist_score_history.term
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	public Integer getTerm() {

		return term;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column nuist_score_history.term
	 * @param term  the value for nuist_score_history.term
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	public void setTerm( Integer term ) {

		this.term = term;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column nuist_score_history.score
	 * @return  the value of nuist_score_history.score
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	public Double getScore() {

		return score;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column nuist_score_history.score
	 * @param score  the value for nuist_score_history.score
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	public void setScore( Double score ) {

		this.score = score;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column nuist_score_history.time
	 * @return  the value of nuist_score_history.time
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	public Date getTime() {

		return time;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column nuist_score_history.time
	 * @param time  the value for nuist_score_history.time
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	public void setTime( Date time ) {

		this.time = time;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column nuist_score_history.credit
	 * @return  the value of nuist_score_history.credit
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	public Double getCredit() {

		return credit;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column nuist_score_history.credit
	 * @param credit  the value for nuist_score_history.credit
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	public void setCredit( Double credit ) {

		this.credit = credit;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column nuist_score_history.grade
	 * @return  the value of nuist_score_history.grade
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	public String getGrade() {

		return grade;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column nuist_score_history.grade
	 * @param grade  the value for nuist_score_history.grade
	 * @ibatorgenerated  Sat Jun 27 15:52:38 CST 2015
	 */
	public void setGrade( String grade ) {

		this.grade = grade;
	}
}