package com.linklife.domain.ibator;

public class NuistTestHistory {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column nuist_test.test_id
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    private Integer testId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column nuist_test.xxx
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    private String xxx;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column nuist_test.test_id
     *
     * @return the value of nuist_test.test_id
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    public Integer getTestId() {
        return testId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column nuist_test.test_id
     *
     * @param testId the value for nuist_test.test_id
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column nuist_test.xxx
     *
     * @return the value of nuist_test.xxx
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    public String getXxx() {
        return xxx;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column nuist_test.xxx
     *
     * @param xxx the value for nuist_test.xxx
     *
     * @ibatorgenerated Mon Feb 23 22:01:52 CST 2015
     */
    public void setXxx(String xxx) {
        this.xxx = xxx;
    }
}