package com.linklife.domain.ibator;

import java.util.Date;

import com.linklife.domain.base.BaseDomain;
import com.linklife.repository.base.SqlMap;

/**
 * <p>
 * NuistSuggest.java
 * </p>
 * 
 * <pre>
 * 南信大一卡�?�用户反馈实�?
 * </pre>
 * 
 * @author caisupeng
 */
@SqlMap(Name = "nuist_suggest", Class = NuistSuggest.class)
public class NuistSuggest<T, U> extends BaseDomain<T, U> {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_suggest.suggest_id
	 * 
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	private Integer suggestId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_suggest.account_id
	 * 
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	private Integer accountId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_suggest.parent_id
	 * 
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	private Integer parentId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_suggest.username
	 * 
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	private String username;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_suggest.usernumber
	 * 
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	private String usernumber;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_suggest.suggest
	 * 
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	private String suggest;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column nuist_suggest.addtime
	 * 
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	private Date addtime;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_suggest.suggest_id
	 * 
	 * @return the value of nuist_suggest.suggest_id
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	public Integer getSuggestId() {
		return suggestId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_suggest.suggest_id
	 * 
	 * @param suggestId
	 *            the value for nuist_suggest.suggest_id
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	public void setSuggestId(Integer suggestId) {
		this.suggestId = suggestId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_suggest.account_id
	 * 
	 * @return the value of nuist_suggest.account_id
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	public Integer getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_suggest.account_id
	 * 
	 * @param accountId
	 *            the value for nuist_suggest.account_id
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_suggest.parent_id
	 * 
	 * @return the value of nuist_suggest.parent_id
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_suggest.parent_id
	 * 
	 * @param parentId
	 *            the value for nuist_suggest.parent_id
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_suggest.username
	 * 
	 * @return the value of nuist_suggest.username
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_suggest.username
	 * 
	 * @param username
	 *            the value for nuist_suggest.username
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_suggest.usernumber
	 * 
	 * @return the value of nuist_suggest.usernumber
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	public String getUsernumber() {
		return usernumber;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_suggest.usernumber
	 * 
	 * @param usernumber
	 *            the value for nuist_suggest.usernumber
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	public void setUsernumber(String usernumber) {
		this.usernumber = usernumber;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_suggest.suggest
	 * 
	 * @return the value of nuist_suggest.suggest
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	public String getSuggest() {
		return suggest;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_suggest.suggest
	 * 
	 * @param suggest
	 *            the value for nuist_suggest.suggest
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	public void setSuggest(String suggest) {
		this.suggest = suggest;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column nuist_suggest.addtime
	 * 
	 * @return the value of nuist_suggest.addtime
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column nuist_suggest.addtime
	 * 
	 * @param addtime
	 *            the value for nuist_suggest.addtime
	 * @ibatorgenerated Mon Jul 27 13:37:47 CST 2015
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}
}