package com.linklife.domain.ibator;

import java.util.Date;

import com.linklife.domain.base.BaseDomain;
import com.linklife.repository.base.SqlMap;

/**
 * <p>
 * SearchHistory.java
 * </p>
 * 
 * <pre>
 * 用户搜索历史表对应实体类
 * </pre>
 * 
 * @author caisupeng
 */
@SqlMap(Name = "search_history", Class = SearchHistory.class)
public class SearchHistory<T, U> extends BaseDomain<T, U> {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column search_history.search_id
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	private Integer searchId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column search_history.email
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	private String email;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column search_history.time
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	private Date time;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column search_history.city
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	private String city;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column search_history.keyword
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	private String keyword;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column search_history.search_ip
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	private String searchIp;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column search_history.search_id
	 * @return  the value of search_history.search_id
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public Integer getSearchId() {
		return searchId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column search_history.search_id
	 * @param searchId  the value for search_history.search_id
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public void setSearchId(Integer searchId) {
		this.searchId = searchId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column search_history.email
	 * @return  the value of search_history.email
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column search_history.email
	 * @param email  the value for search_history.email
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column search_history.time
	 * @return  the value of search_history.time
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column search_history.time
	 * @param time  the value for search_history.time
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column search_history.city
	 * @return  the value of search_history.city
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column search_history.city
	 * @param city  the value for search_history.city
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column search_history.keyword
	 * @return  the value of search_history.keyword
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public String getKeyword() {
		return keyword;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column search_history.keyword
	 * @param keyword  the value for search_history.keyword
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column search_history.search_ip
	 * @return  the value of search_history.search_ip
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public String getSearchIp() {
		return searchIp;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column search_history.search_ip
	 * @param searchIp  the value for search_history.search_ip
	 * @ibatorgenerated  Tue Aug 19 11:37:43 CST 2014
	 */
	public void setSearchIp(String searchIp) {
		this.searchIp = searchIp;
	}
}